🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/__mailsync b/bin/__mailsync
--- a/bin/__mailsync
+++ b/bin/__mailsync
@@ -1,39 +1,59 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="__mailsync"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : __mailsync
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : sync your email
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211026-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : __mailsync --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 10:26 EST
+# @File          : __mailsync
+# @Description   : sync your email
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-__mailsync() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  __mailsync    |    sync your email
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo -e "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "__mailsync    |    sync your email"
-
-  if cmd_exists mailsync; then
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if [ -f "$(command -v mailsync 2>/dev/null)" ]; then
     printf_green "Syncing Mailboxes with mailsync"
-    mailsync >/dev/null 2>&1 || printf_red "Mail Sync Failed"
+    if mailsync &>/dev/null; then
+      return 0
+    else
+      printf_red "Mail Sync Failed"
+      return 1
+    fi
+  else
+    return 1
   fi
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-__mailsync "$@"
+__main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/__muttsync b/bin/__muttsync
--- a/bin/__muttsync
+++ b/bin/__muttsync
@@ -1,40 +1,70 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="_muttsync"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : _muttsync
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : sync your email with mutt
-#
+#set opts
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211137-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : _muttsync --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 11:37 EST
+# @File          : _muttsync
+# @Description   :
+# @TODO          :
+# @Other         :
+# @Resource      :
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# check for required
+cmd_exists --error mbsync || exit 1
 # Main function
-
-__muttsync() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help(){
+  printf_help "_muttsync    |    sync your email with mutt"
+}
+main() {
+  local DIR="${BASH_SOURCE%/*}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "_muttsync    |    sync your email with mutt"
-
-  if cmd_exists mbsync; then
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  notify() { [ -f "$(command -v notifications 2>/dev/null)" ] && notifications "$@" || return 1; }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if am_i_online; then
     printf_green "Syncing Mailboxes with mbsync"
-    /usr/bin/mbsync -a >/dev/null 2>&1 ||
+    notify "Mail" "Syncing Mailboxes with mbsync"
+    if /usr/bin/mbsync -a >/dev/null 2>&1; then
+      printf_green "mail has been synced"
+      notify "mbsync" "mail has been synced"
+      return 0
+    else
       printf_red "Mail Sync Failed"
+      notify "mbsync" "Mail Sync Failed"
+      return 1
+    fi
+  else
+    printf_red "Mail Sync Failed"
+    notify "mbsync" "Mail Sync Failed"
+    return 1
   fi
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-__muttsync "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/checkup b/bin/checkup
--- a/bin/checkup
+++ b/bin/checkup
@@ -1,51 +1,66 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="checkup"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : checkup
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : check for updates on Arch
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210423-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : checkup --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 04:23 EST
+# @File          : checkup
+# @Description   : check for system updates
+# @TODO          : make compatible with all package managers
+# @Other         : used primarily by i3
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-checkup() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
-  else
-    echo -e "\t\tCouldn't source the functions file"
-    exit 1
-  fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: checkup    |   Check for pacman updates"
-
-  ping -q -c 1 1.1.1.1 >/dev/null || exit 1
-
-  if cmd_exists pacman; then
-    notifications "📦 Repository Sync" "Checking for package updates..."
-    sudo pacman -Syyuw --noconfirm || notifications "Error downloading updates."
-
-    #Check your internet connection, if pacman is already running, or run update manually to see errors."
-    if [ -n "${STATUSBAR}" ]; then pkill -RTMIN+8 "${STATUSBAR:?}"; fi
-
-    if pacman -Qu | grep -v "\[ignored\]"; then
-      notifications "🎁 Repository Sync" "Updates available."
-    else
-      notifications "📦 Repository Sync" "Sync complete. No new packages for update."
-    fi
-
-  fi
+__help() {
+  printf_help "Usage: checkup  |  Check for package updates"
 }
-
+checkup() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __pacman() { am_i_online && sudo pacman "$@" || return 1; }
+  if [ "$(command -v pacman)" ]; then
+    notifications "📦 Repository Sync" "Checking for package updates..."
+    if __pacman -Syyuw --noconfirm; then
+      if __pacman -Qu | grep -v "\[ignored\]"; then
+        notifications "🎁 Repository Sync" "Updates available."
+      else
+        notifications "📦 Repository Sync" "Sync complete. No new packages for update."
+      fi
+      local exitCode=0
+    else
+      notifications "Error downloading updates."
+      local exitCode=1
+    fi
+    [ -n "${STATUSBAR}" ] && pkill -RTMIN+8 "${STATUSBAR:?}"
+  else
+    local exitCode=1
+  fi
+  return "${exitCode:-$?}"
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
 checkup "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# end
diff --git a/bin/cmd_exists b/bin/cmd_exists
--- a/bin/cmd_exists
+++ b/bin/cmd_exists
@@ -1,37 +1,66 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="cmd_exists"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : cmd_exists
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : check if a script exists
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210447-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : cmd_exists --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 04:47 EST
+# @File          : cmd_exists
+# @Description   : check if a script exists
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-if [ ! -f "$(command -v cmd_exists 2>/dev/null)" ]; then
-  cmd_exists() {
-    DIR="${BASH_SOURCE%/*}"
-    if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
-    if [[ -f "$DIR/functions.bash" ]]; then
-      source "$DIR/functions.bash"
-    else
-      echo -e "\t\tCouldn't source the functions file"
-      exit 1
-    fi
-
-    [ ! "$1" = "--help" ] || printf_help "Usage: cmd_exists cmd"
-
-    command -v "$1" &>/dev/null
-  }
-
+__help() {
+  printf_help "Usage: cmd_exists cmd  |  cmd_exists bash fish zsh"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  # execute function
-  cmd_exists "$@"
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  case "$1" in
+    *err*) local error=show && shift 1;;
+  esac
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  local exitCode=0
+  local missing=""
+  for f in "$@"; do
+    if [ -f "$(command -v "$f")" ]; then
+      exitCode+=0
+    else
+      missing="$f "
+      exitCode+=1
+    fi
+  done
+  if [ "$error" = "show" ] && [ -n "$missing" ]; then
+    printf_red "Missing: $missing"
+    exitCode="1"
+  fi
+  return "${exitCode:-$?}"
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-fi
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# end
diff --git a/bin/copy b/bin/copy
--- a/bin/copy
+++ b/bin/copy
@@ -1,43 +1,61 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="copy"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : copy
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : copies a file and shows progress
-#
+#set opts
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210522-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : copy --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 05:22 EST
+# @File          : copy
+# @Description   : copies a file and shows progress
+# @TODO          :
+# @Other         :
+# @Resource      :
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+cmd_exists --err dd || exit 1
 # Main function
-
-copy() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help "Usage: copy source destination  |  copy file1 file2"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: copy /source/file /destination/file"
-
-  [[ -z "$1" || -z "$2" ]] && {
-    printf_red "Usage: copy /source/file /destination/file"
-    exit 1
-  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  [ -z "$1" ] || [ -z "$2" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  typeset src="$1"
   typeset dest="$2"
-  typeset size=$(stat -c%s "$1")
-  [[ -d "$dest" ]] && dest="$2/$(basename "$1")"
-  dd if="$1" 2>/dev/null | pv -petrb -s "$size" | dd of="$dest"
+  typeset size=$(stat -c%s "$src")
+  [[ -d "$dest" ]] && dest="$dest/$(basename "$src")"
+  if [ -f "$(command -v pv)" ]; then
+    dd if="$src" 2>/dev/null | pv -petrb -s "$size" 2>/dev/null | dd of="$dest" 2>/dev/null
+  else
+    dd if="$src" of="$dest" status=progress 2>/dev/null
+  fi
+  return $?
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-copy "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/countdown b/bin/countdown
--- a/bin/countdown
+++ b/bin/countdown
@@ -1,44 +1,65 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="countdown"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : timer
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : shows up/down seconds counter. Exits and produces a sound if reaches zero
-#
+#set opts
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210605-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : countdown --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 06:05 EST
+# @File          : countdown
+# @Description   : shows up/down seconds counter. Exits and produces a sound if reaches zero
+# @TODO          :
+# @Other         :
+# @Resource      :
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+cmd_exists --error showbanner || exit 1
 # Main function
-
+__help() {
+  printf_help "Usage: countdown howLong  |  countdown 300"
+}
 timer() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: timer howLong"
-
-  typeset ts="$(($(date +%s) + ${1:-0} - 1))"
-  export ts
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  local d="$1"
+  typeset ts="$(($(date +%s) + ${1:-0} - 1))"; export ts
   typeset p1="d=$(($(date +%s) - $ts));[ $d -lt 0 ] && d=$((-d));"
   typeset p2="[ $d -eq 0 ] && exit 1;"
   typeset p3="date -u -d @"$d" +"%H.%M.%S""
   showbanner -t.5 "$p1$p2$p3"
   typeset status="$?"
   eval "$p1$p3"
-  [[ "$status" -eq 8 ]] && speaker-test -t sine -f 1500 -S 70 -p 10000 -l 1 &>/dev/null
+  if [[ "$status" -eq 8 ]]; then
+    notifications "Timer" "Your timer has gone off"
+    if [[ -f "$(command -v speaker-test)" ]]; then
+      speaker-test -t sine -f 1500 -S 70 -p 10000 -l 1 &>/dev/null
+    elif [[ -f "$(command -v say)" ]]; then
+      say "Your timer is going off"
+    fi
+  fi
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
 timer "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/datauri b/bin/datauri
--- a/bin/datauri
+++ b/bin/datauri
@@ -1,47 +1,60 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="datauri"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : datauri
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Create data URI from a file
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210622-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : datauri --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 06:22 EST
+# @File          : datauri
+# @Description   : Create data URI from a file
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-datauri() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help "Usage: datauri fileName"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: datauri fileName"
-
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   typeset mimeType=""
   if [ -f "$1" ]; then
     mimeType=$(file -b --mime-type "$1")
     if [[ $mimeType == text/* ]]; then
       mimeType="$mimeType;charset=utf-8"
     fi
-    printf "data:%s;base64,%s" \
-      "$mimeType" \
-      "$(openssl base64 -in "$1" | tr -d "\n")"
+    printf "data:%s;base64,%s" "$mimeType" "$(openssl base64 -in "$1" | tr -d "\n")"
+    echo ""
   else
     printf "%s is not a file.\n" "$1"
+    return 1
   fi
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-datauri "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/delhistory b/bin/delhistory
--- a/bin/delhistory
+++ b/bin/delhistory
@@ -1,32 +1,43 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="delhistory"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : delhistory
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : remove last n records from history
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210628-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : delhistory --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 06:28 EST
+# @File          : delhistory
+# @Description   : remove last n records from history
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-delhistory() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help "Usage delhistory Number  |  delhistory 10"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
     source "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage delhistory Number"
-
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   typeset opt id n=1
   OPTIND=1 #reset index
   while getopts "n:" opt; do
@@ -35,7 +46,7 @@ delhistory() {
     \?) exit 1 ;;
     :)
       printf_red "Option -$OPTARG requires number of history last entries to remove as an argument" >&2
-      exit 1
+      return 1
       ;;
     esac
   done
@@ -43,9 +54,12 @@ delhistory() {
   ((++n))
   id=$(history | tail -n $n | head -n1 | awk '{print $1}')
   while ((n-- > 0)); do history -d "$id"; done
+  return $?
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-delhistory "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/ex b/bin/ex
--- a/bin/ex
+++ b/bin/ex
@@ -1,32 +1,43 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="ex"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : ex
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : ex - archive extractor
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210633-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : ex --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 06:33 EST
+# @File          : ex
+# @Description   : archive extractor
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-ex() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help "Usage: ex fileName"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: ex fileName"
-
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   if [ -f $1 ]; then
     case $1 in
     *.tar.bz2) tar xjf $1 ;;
@@ -40,14 +51,19 @@ ex() {
     *.zip) unzip $1 ;;
     *.Z) uncompress $1 ;;
     *.7z) 7z x $1 ;;
-    *) printf_red "$1 cannot be extracted via ex()" ;;
+    *) printf_red "$1 cannot be extracted via ex()" && return 1;;
     esac
+    return $?
   else
     printf_red "$1 is not a valid file"
+    return 1
   fi
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-ex "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/git_clone b/bin/git_clone
--- a/bin/git_clone
+++ b/bin/git_clone
@@ -1,43 +1,61 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="git_clone"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : git_clone
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : clone a git repo and delete the directory if it exits
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210655-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : git_clone --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 06:55 EST
+# @File          : git_clone
+# @Description   : clone a git repo and delete the directory if it exits
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-git_clone() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help "Usage: git_clone remote local | This will delete the local directory if it exists"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: git_clone remote local | This will delete the local directory if it exists"
-
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   printf_question "Are you sure as this WILL delete your local repo" [y/N]
   read -r -n 1 -s clone && echo
   if [[ $clone == "y" || $clone == "Y" ]]; then
-    rm_rf "$2"
-    devnull git clone -q "$@"
+    [ -d "$2" ] && rm_rf "$2"
+    if [ -d "$1" ]; then
+      devnull git clone -q "$@" && return 0 || return 1
+    else
+      am_i_online && devnull git clone -q "$@" && return 0 || return 1
+    fi
   else
     printf_info "You have cancelled the current operation"
+    return 1
   fi
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-git_clone "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/git_update b/bin/git_update
--- a/bin/git_update
+++ b/bin/git_update
@@ -1,36 +1,49 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="git_update"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR=="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : git_update
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : clone a git repo and delete the directory if it exits
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210721-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : git_update --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 07:21 EST
+# @File          : git_update
+# @Description   : update the git repo
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-git_update() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
-  else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
-  fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: git_update | Must be in a git repo"
-
-  git pull -qf
+__help() {
+  printf_help "Usage: git_update | Must be in a git repo"
 }
-
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ ! "$1" = "--help" ] || printf_help "Usage: git_update | Must be in a git repo"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  git -C "${1:-.}" pull -qf && return 0 || return 1
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-git_update "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/gitforcepull b/bin/gitforcepull
--- a/bin/gitforcepull
+++ b/bin/gitforcepull
@@ -1,43 +1,58 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="gitforcepull"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : gitforcepull
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : pull a git repo and hard reset
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210704-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : gitforcepull --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 07:04 EST
+# @File          : gitforcepull
+# @Description   : pull a git repo and do hard reset
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-gitforcepull() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help "Usage: gitforcepull | This will reset the repo and do a pull"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: gitforcepull | This will reset the repo"
-
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   printf_question "Are you sure as this WILL reset your local changes" [y/N]
   read -r -n 1 -s fpull && echo
   if [[ $fpull == "y" || $fpull == "Y" ]]; then
-    git reset -q --hard HEAD
-    git pull -fq
+    git -C "${1:-.}" reset -q --hard HEAD &&
+    git -C "${1:-.}" pull -fq && return 0 || return 1
   else
     printf_info "You have cancelled the current operation"
+    return 1
   fi
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-gitforcepull "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/gitforcepush b/bin/gitforcepush
--- a/bin/gitforcepush
+++ b/bin/gitforcepush
@@ -1,41 +1,56 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="gitforcepush"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : gitforcepush
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : force a git push
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210710-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : gitforcepush --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 07:10 EST
+# @File          : gitforcepush
+# @Description   : force a git push
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-gitforcepush() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help "Usage: gitforcepush | This will overwrite the remote repo"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: gitforcepush | This will overwrite the remote repo"
-
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   printf_question "Are you sure as this overwrite your remote repo" [y/N]
   read -r -n 1 -s fpush && echo
   if [[ $fpush == "y" || $fpush == "Y" ]]; then
-    git push -f
+    git -C "${1:-.}" push -f -q && return 0 || return 1
   else
     printf_info "You have cancelled the current operation"
+    return 1
   fi
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-gitforcepush "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/gz b/bin/gz
--- a/bin/gz
+++ b/bin/gz
@@ -1,32 +1,44 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="gz"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : gz
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Get gzip information (gzipped file size + reduction size).
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210722-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : gz --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 07:22 EST
+# @File          : gz
+# @Description   : Get gzip information (gzipped file size + reduction size).
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-gz() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+cmd_exists --error hrfs || exit 1
+__help() {
+  printf_help "Usage: gz fileName"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: gz fileName"
-
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   declare -i gzippedSize=0
   declare -i originalSize=0
   if [ -f "$1" ]; then
@@ -40,16 +52,21 @@ gz() {
         "$(hrfs $((originalSize - gzippedSize)))" \
         "$(printf "%s" "$originalSize $gzippedSize" |
           awk '{ printf "%.1f", 100 - $2 * 100 / $1 }' |
-          sed -e "s/0*$//;s/\.$//")"
+          sed -e "s/0*$//;s/\.$//")" || return 1
     else
       printf "\"%s\" is empty.\n" "$1"
+      return 1
     fi
   else
     printf "\"%s\" is not a file.\n" "$1"
+    return 1
   fi
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-gz "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/hrfs b/bin/hrfs
--- a/bin/hrfs
+++ b/bin/hrfs
@@ -1,59 +1,67 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="hrfs"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : hrfs
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Human readable file size - (because `du -h` doesn't cut it for me).
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210748-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : hrfs --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 07:48 EST
+# @File          : hrfs
+# @Description   : Human readable file size - because du -h doesn't cut it for me.
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-hrfs() {
-    DIR="${BASH_SOURCE%/*}"
-    if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
-    if [[ -f "$DIR/functions.bash" ]]; then
-        source "$DIR/functions.bash"
-    else
-        echo "\t\tCouldn't source the functions file"
-        exit 1
-    fi
-
-    [ ! "$1" = "--help" ] || printf_help "Human readable file size"
-
-    printf "%s" "$1" |
-        awk '{
-            i = 1;
-            split("B KB MB GB TB PB EB ZB YB WTFB", v);
-            value = $1;
-
-            # confirm that the input is a number
-            if ( value + .0 == value ) {
-
-                while ( value >= 1024 ) {
-                    value/=1024;
-                    i++;
-                }
-
-                if ( value == int(value) ) {
-                    printf "%d %s", value, v[i]
-                } else {
-                    printf "%.1f %s", value, v[i]
-                }
-
-            }
-        }' |
-        sed -e ":l" \
-            -e "s/\([0-9]\)\([0-9]\{3\}\)/\1,\2/; t l"
+__help() {
+    printf_help "usage: hrfs file  |  Human readable file size"
 }
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  printf "%s" "$1" |
+    awk '{
+      i = 1;
+      split("B KB MB GB TB PB EB ZB YB WTFB", v);
+      value = $1;
+      if ( value + .0 == value ) {
+        while ( value >= 1024 ) {
+          value/=1024;
+          i++;
+      }
 
+      if ( value == int(value) ) {
+        printf "%d %s", value, v[i]
+          } else {
+            printf "%.1f %s", value, v[i]
+          }
+
+      }
+    }' | sed -e ":l" -e "s/\([0-9]\)\([0-9]\{3\}\)/\1,\2/; t l" && return 0 || return 1
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-hrfs "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/linkhandler b/bin/linkhandler
--- a/bin/linkhandler
+++ b/bin/linkhandler
@@ -1,48 +1,85 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-# Feed script a url or file location.
-# If an image, it will view in sxiv,
-# if a video or gif, it will view in mpv
-# if a music file or pdf, it will download,
-# otherwise it opens link in browser.
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="linkhandler"
+USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
-# If no url given. Opens browser. For using script as $BROWSER.
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+#set opts
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210756-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : linkhandler --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 07:56 EST
+# @File          : linkhandler
+# @Description   : Feed script a url or file location.
+# @TODO          :
+# @Other         :
+# @Resource      :
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+cmd_exists --error setsid || exit 1
+# Main function
+__help() {
+  printf_help "Usage: linkhander pathtofile or url"
+}
 main() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: linkhander pathtofile or url"
-
-  [ -z "$1" ] && {
-    "$BROWSER"
-    exit
-  }
-
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ -z "$1" ] && { "$BROWSER" && exit; }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   case "$1" in
   *mkv | *webm | *mp4 | *youtube.com/watch* | *youtube.com/playlist* | *youtu.be* | *hooktube.com* | *bitchute.com*)
-    setsid mpv --input-ipc-server=/tmp/mpvsoc$(date +%s) -quiet "$1" >/dev/null 2>&1 &
+    if [ -f "$(command -v mpv)" ]; then
+      setsid mpv --input-ipc-server=/tmp/mpvsoc$(date +%s) -quiet "$1" &>/dev/null && return 0 || return 1 &
+    else
+      return 1
+    fi
     ;;
   *png | *jpg | *jpe | *jpeg | *gif)
-    curl -sL "$1" >"/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")" >/dev/null 2>&1 &
+    if [ -f "$(command -v sxiv)" ]; then
+      curl -sL "$1" >"/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")" &>/dev/null && return 0 || return 1 &
+    else
+      return 1
+    fi
     ;;
   *mp3 | *flac | *opus | *mp3?source*)
-    setsid tsp curl -LO "$1" >/dev/null 2>&1 &
+    if [ -f "$(command -v tsp)" ]; then
+      setsid tsp curl -LO "$1" &>/dev/null && return 0 || return 1 &
+    elif [ -f "$(command -v deadbeef)" ]; then
+      setsid deadbeef "$1"  &>/dev/null && return 0 || return 1 &
+    else
+      return 1
+    fi
+    ;;
+  *htm*)
+    setsid "$BROWSER" "$1" &>/dev/null && return 0 || return 1 &
     ;;
   *)
     if [ -f "$1" ]; then
-      "$TERMINAL" -e "$EDITOR $1"
+      "$TERMINAL" -e "$EDITOR $1" &>/dev/null && return 0 || return 1 &
     else
-      setsid "$BROWSER" "$1" >/dev/null 2>&1 &
+      setsid "$BROWSER" "$1" &>/dev/null && return 0 || return 1 &
     fi
     ;;
   esac
 }
-
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/lso b/bin/lso
--- a/bin/lso
+++ b/bin/lso
@@ -1,36 +1,52 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="lso"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : lso
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : adds files permissons in binary form to the ls command output
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120210815-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : lso --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 08:15 EST
+# @File          : lso
+# @Description   : adds files permissons in binary form to the ls command output
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-lso() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
-  else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
-  fi
-
-  [ ! "$1" = "--help" ] || printf_help "adds files permissons in binary form to the ls command output"
-
-  if [ -t 0 ]; then ls -alG "$@"; else cat -; fi | awk '{t=$0;gsub(/\x1B\[[0-9;]*[mK]/,"");k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(" %0o ",k);print t}'
+__help() {
+  printf_help "lso filename  |  adds files permissons in binary form to the ls command output"
 }
-
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if [ ! -e "$1" ]; then printf_red "cannot access $1: No such file or directory" && return 1; fi
+  if [ -t 0 ]; then ls --color -alG "${@:-.}"; else cat -; fi | \
+    awk '{t=$0;gsub(/\x1B\[[0-9;]*[mK]/,"");k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(" %0o ",k);print t}'
+  return $?
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-lso "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/maimpick b/bin/maimpick
--- a/bin/maimpick
+++ b/bin/maimpick
@@ -1,14 +1,48 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-# This is bound to Shift+PrintScreen by default, requires maim. It lets you
-# choose the kind of screenshot to take, including copying the image or even
-# highlighting an area to copy. scrotcucks on suicidewatch right now.
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="maimpick"
+USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211036-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : maimpick --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 10:36 EST
+# @File          : maimpick
+# @Description   : screenshot utility using maim
+# @TODO          :
+# @Other         :
+# @Resource      :
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+cmd_exists --error maim || exit 1
+__help() {
+  printf_help "Usage: maim     |    screenshot utility"
+}
 main() {
-  [ ! "$1" = "--help" ] || printf_help "Usage: maim     |    screenshot utility"
-
-  pkmgr ask maim || exit 1
-
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    source "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  local IMAGE_DIR="$HOME/Pictures/maim"
+  local IMG="$IMAGE_DIR/$(date '+%y%m%d-%H%M-%S').png"
+  mkdir -p "$IMAGE_DIR" &>/dev/null
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   case "$(printf "a selected area\\ncurrent window\\nfull screen\\na selected area (copy)\\ncurrent window (copy)\\nfull screen (copy)" | dmenu -l 6 -i -p "Screenshot which area?")" in
   "a selected area") maim -s pic-selected-"$(date '+%y%m%d-%H%M-%S').png" ;;
   "current window") maim -i "$(xdotool getactivewindow)" pic-window-"$(date '+%y%m%d-%H%M-%S').png" ;;
@@ -16,7 +50,12 @@ main() {
   "a selected area (copy)") maim -s | xclip -selection clipboard -t image/png ;;
   "current window (copy)") maim -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
   "full screen (copy)") maim | xclip -selection clipboard -t image/png ;;
-  esac
+esac
+return $?
 }
-
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/mastodon b/bin/mastodon
--- a/bin/mastodon
+++ b/bin/mastodon
@@ -1,38 +1,52 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="mastodon"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : mastodon
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Post to mastodon
-#
+#set opts
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211052-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : mastodon --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 10:52 EST
+# @File          : mastodon
+# @Description   :
+# @TODO          :
+# @Other         :
+# @Resource      :
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+cmd_exists --error toot || exit 1
 # Main function
-
-mastodon() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+     "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--version" ] || get_app_info "$APPNAME"
-
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [ ! "$1" = "--help" ] || printf_help "Usage: mastodon 'MyMessage'"
-
-  toot post "$@"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if am_i_online; then
+    toot post "$@" && return 0 || return 1
+  else
+    return 1
+  fi
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-mastodon "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/mkd b/bin/mkd
--- a/bin/mkd
+++ b/bin/mkd
@@ -1,47 +1,65 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="mkd"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : mkd
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Create new directories and enter the first one
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211101-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : mkd --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 11:01 EST
+# @File          : mkd
+# @Description   : create directory and cd into it
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-mkd() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help "Usage: mkd directorytoCreate"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  CREATE="$1"
-  __help() { printf_help "Usage: mkd directorytoCreate"; }
-  [ ! "$1" = "--help" ] || __help
-  if [ $# -ne 1 ]; then __help; fi
-
-  typeset dir="$CREATE"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  [ $# -ne 1 ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  local CREATE="$1"
+  __cd() { cd "$1" && bash || return 1; }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   if [ -n "$CREATE" ]; then
-    printf_green "Creating $CREATE and entering the directory"
-    mkdir -p "$CREATE"
-    printf_green "Type exit to return to your previous directory"
-    cd "$CREATE" && bash || return 1
+    if mkdir -p "$CREATE" &>/dev/null; then
+      printf_green "Creating $CREATE and entering the directory"
+      printf_green "Type exit to return to your previous directory" && __cd "$CREATE" && exitCode=0 || exitCode=1
+    else
+      printf_red "Failed to create $CREATE"
+      exitCode=1
+    fi
   else
     printf_red "Usage: mkd folder"
+    exitCode=1
   fi
+  return ${exitCode:-$?}
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-mkd "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/pass b/bin/pass
--- a/bin/pass
+++ b/bin/pass
@@ -1,20 +1,43 @@
 #!/usr/bin/env bash
 
-# Copyright (C) 2012 - 2018 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
-# This file is licensed under the GPLv2+. Please see COPYING for more information.
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="pass"
+USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211934-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : pass --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 19:34 EST
+# @File          : pass
+# @Description   : Pass is a password manager written in bash
+# @TODO          :
+# @Other         :
+# @Resource      :
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+__help() {
+  printf_help "Usage: pass"
+}
 main() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: pass"
-
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && printf_help "Usage: pass"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   umask "${PASSWORD_STORE_UMASK:-077}"
   set -o pipefail
 
@@ -191,7 +214,7 @@ main() {
     pkill -f "^$sleep_argv0" 2>/dev/null && sleep 0.5
     local before="$("${paste_cmd[@]}" 2>/dev/null | $BASE64)"
     echo -n "$1" | "${copy_cmd[@]}" || die "Error: Could not copy data to the clipboard"
-    ( 
+    (
       (exec -a "$sleep_argv0" bash <<<"trap 'kill %1' TERM; sleep '$CLIP_TIME' & wait")
       local now="$("${paste_cmd[@]}" | $BASE64)"
       [[ $now != $(echo -n "$1" | $BASE64) ]] && before="$now"
@@ -838,5 +861,9 @@ main() {
   esac
   exit 0
 }
-
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/pauseallmpv b/bin/pauseallmpv
--- a/bin/pauseallmpv
+++ b/bin/pauseallmpv
@@ -1,25 +1,56 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-# You might notice all mpv commands are aliased to have this input-ipc-server
-# thing. That's just for this particular command, which allows us to pause
-# every single one of them with one command! This is bound to super + shift + p
-# (with other things) by default and is used in some other places.
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="pauseallmpv"
+USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
-main() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
-  else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
-  fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+#set opts
 
-  [ ! "$1" = "--help" ] || printf_help "Usage: pauseallmpv    |    pause mpv"
-
-  for i in $(ls /tmp/mpvsoc*); do
-    echo '{ "command": ["set_property", "pause", true] }' | socat - $i
-  done
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211143-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : pauseallmpv --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 11:43 EST
+# @File          : pauseallmpv
+# @Description   : Pause all mpv processes
+# @TODO          :
+# @Other         :
+# @Resource      :
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+cmd_exists mpv socat || exit 1
+# main function
+__help() {
+  printf_help "Usage: pauseallmpv    |    pause mpv"
 }
-
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if $(find /tmp/mpvsoc* 2>/dev/null); then
+    for i in $(ls /tmp/mpvsoc* 2>/dev/null); do
+      echo '{ "command": ["set_property", "pause", true] }' | socat - $i && exitCode=0 || exitCode=1
+    done
+  else
+    exitCode=1
+  fi
+  return ${exitCode:-$?}
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/ppi b/bin/ppi
--- a/bin/ppi
+++ b/bin/ppi
@@ -1,33 +1,44 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="ppi"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : ppi
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Process phone images
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211205-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : ppi --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 12:05 EST
+# @File          : ppi
+# @Description   : Process phone images.
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-ppi() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help "Usage: ppi pathtoFile"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: ppi pathtoFile"
-
-  cmd_exists convert || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  reqpack=imagemagick cmd_exists --error convert || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   typeset query="${1:-*.jpg}"
   typeset geometry="${2:-50%}"
   for i in "$query"; do
@@ -48,14 +59,14 @@ ppi() {
       -gravity center \
       -resize "$geometry" \
       +append \
-      "$imgName" &&
-      printf "* %s (%s)\n" \
-        "$imgName" \
-        "$geometry"
-  done
+      "$imgName" && printf "* %s (%s)\n"  "$imgName" "$geometry" || return 1
+      done && exitCode+=0 || exitCode=1
+  return ${exitCode:-$?}
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-ppi "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/prompt b/bin/prompt
--- a/bin/prompt
+++ b/bin/prompt
@@ -1,23 +1,48 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-# A dmenu binary prompt script.
-# Gives a dmenu prompt labeled with $1 to perform command $2.
-# For example:
-# `./prompt "Do you want to shutdown?" "shutdown -h now"`
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="prompt"
+USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
-main() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
-  else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
-  fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+#set opts
 
-  [ ! "$1" = "--help" ] || printf_help "Usage: prompt message action    |    custom dmenu prompt"
-
-  [ "$(printf "No\\nYes" | dmenu -i -p "$1" -nb darkred -sb red -sf white -nf gray)" = "Yes" ] && $2
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211216-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : prompt --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 12:16 EST
+# @File          : prompt
+# @Description   : A dmenu binary prompt script.
+# @TODO          :
+# @Other         :
+# @Resource      :
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# main function
+__help () {
+  printf_help "Usage: prompt message action    |    custom dmenu prompt"
 }
-
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$(printf "No\\nYes" | dmenu -i -p "$1" -nb darkred -sb red -sf white -nf gray)" = "Yes" ] && $2 || return 1
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/putclip b/bin/putclip
--- a/bin/putclip
+++ b/bin/putclip
@@ -4,40 +4,55 @@
 PROG="putclip"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 031120210233-git
+##@Version       : 031120211507-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
 # @License       : WTFPL
 # @ReadME        : putclip --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Thursday, Mar 11, 2021 02:33 EST
+# @Created       : Thursday, Mar 11, 2021 15:07 EST
 # @File          : putclip
 # @Description   : copy input to clipboard
 # @TODO          :
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [ $# -eq 0 ]; then
+# Main function
+__help() {
+  printf_help "Usage: cmd_exists cmd  |  cmd_exists bash fish zsh"
+}
+DIR="${SRC_DIR:-$PWD}"
+if [[ -f "$DIR/functions.bash" ]]; then
+  . "$DIR/functions.bash"
+else
+  printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+  exit 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+[ "$1" = "--help" ] && __help
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+if [ $# -eq 0 ] && [ -t 0 ]; then
     message="$(</dev/stdin)"
 else
     message="$*"
 fi
 if [[ "$(uname -s)" =~ ^darwin ]]; then
   if [[ -f "$(command -v pbcopy)" ]]; then
-     echo "$message" | LC_CTYPE=UTF-8 tr -d "\n" | pbcopy
+     echo "$message" | LC_CTYPE=UTF-8 tr -d "\n" | pbcopy && exitCode=0 || exitCode=1
   fi
 elif [[ "$(uname -s)" =~ ^linux ]]; then
   if [[ -f "$(command -v xclip)" ]]; then
-    echo "$message" | xclip -i -sel c
+    echo "$message" | xclip -i -sel c && exitCode=0 || exitCode=1
   fi
 else
-  echo "$message" >>"${TMPDIR:-/tmp}/clipboard"
+  echo "$message" >>"${TMPDIR:-/tmp}/clipboard" && exitCode=0 || exitCode=1
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
+exit ${exitCode:-$?}
 # end
diff --git a/bin/qh b/bin/qh
--- a/bin/qh
+++ b/bin/qh
@@ -1,36 +1,63 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="qh"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : qh
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Search through history
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211525-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : qh --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 15:25 EST
+# @File          : qh
+# @Description   : Search through history
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-qh() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
-  else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
-  fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: qh searchPattern"
-
-  grep --color=always "$*" "$HISTFILE" | less -RX
+__help() {
+  printf_help "Usage: qh searchPattern  |  qh ls"
 }
-
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  local LESS_TERMCAP_mb=$'\e[1;32m'
+  local LESS_TERMCAP_md=$'\e[1;32m'
+  local LESS_TERMCAP_me=$'\e[0m'
+  local LESS_TERMCAP_se=$'\e[0m'
+  local LESS_TERMCAP_so=$'\e[01;33m'
+  local LESS_TERMCAP_ue=$'\e[0m'
+  local LESS_TERMCAP_us=$'\e[1;4;31m'
+  local HISTFILE="${HISTFILE:-$HOME/.bash_history}"
+  local SEARCH="$(grep --color=always "$*" "$HISTFILE" | grep '^' || return 1)"
+  if [ -f "$HISTFILE" ] && [ -n "$SEARCH" ]; then
+    echo "$SEARCH" | less -RX
+  else
+    printf_red "No results for $* found"
+    return 1
+  fi
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-qh "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/qrcode b/bin/qrcode
--- a/bin/qrcode
+++ b/bin/qrcode
@@ -1,40 +1,59 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="qrcode"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : qrcode
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : converts text into a qr code
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211549-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : qrcode --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 15:49 EST
+# @File          : qrcode
+# @Description   : converts text into a qr code
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-qrcode() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help 'Usage: qrcode "Item to turn into a qrcode"'
+}
+main() {
+  local DIR="${BASH_SOURCE%/*}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help 'Usage: qrcode "Item to turn into a qrcode"'
-
-  typeset text="$1"
-  [[ -e "$text" ]] && text=$(cat "$text")
-  [[ -z "$text" ]] && [[ ! -t 0 ]] && text=$(cat -)
-  [[ -z "$text" ]] && text=$(printclip)
-  echo "$text" | curl -F-=\<- qrenco.de
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  typeset text="$*"
+  if am_i_online; then
+    [[ -e "$text" ]] && text=$(cat "$text")
+    [[ -z "$text" ]] && [[ ! -t 0 ]] && text=$(cat -)
+    [[ -z "$text" ]] && text=$(printclip)
+    echo "$text" | curl -F-=\<- qrenco.de || return 1
+  else
+    printf_red "No internet connection detected"
+    return 1
+  fi
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-qrcode "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/qt b/bin/qt
--- a/bin/qt
+++ b/bin/qt
@@ -1,36 +1,59 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="qt"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : qt
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Search for text within the current directory
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211602-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : qt --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 16:02 EST
+# @File          : qt
+# @Description   : Search for text within the current directory
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-qt() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help "Usage: qt itemtoFind"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: qt itemtoFind"
-
-  grep -ir --color=always "$*" --exclude-dir=".git" --exclude-dir="node_modules" . | less -RX
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ -d "$1" ] && local SEARCH_DIR="$1" && shift 1 || local SEARCH_DIR="$PWD"
+  local GREP_OPTS="-ir --color=always "$*""
+  local GREP_EXCLUDE="--exclude-dir="$SEARCH_DIR/.git" --exclude-dir="$SEARCH_DIR/node_modules""
+  local SEARCH="$(grep $GREP_OPTS $GREP_EXCLUDE "${SEARCH_DIR:-.}" 2>/dev/null || return 1)"
+  if [ -d "$SEARCH_DIR" ] && [ -n "$SEARCH" ]; then
+    echo "$SEARCH" | less -RX
+  else
+    printf_red "Search returned no results"
+    return 1
+  fi
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-qt "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/renameFilesRecursively b/bin/renameFilesRecursively
--- a/bin/renameFilesRecursively
+++ b/bin/renameFilesRecursively
@@ -4,69 +4,82 @@
 PROG="renameFilesRecursively"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 020920211449-git
+##@Version       : 031120211604-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
-# @License       : LICENSE.md
-# @ReadME        : README.md
+# @License       : WTFPL
+# @ReadME        : renameFilesRecursively --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Tuesday, Feb 09, 2021 15:26 EST
+# @Created       : Thursday, Mar 11, 2021 16:04 EST
 # @File          : renameFilesRecursively
-# @Description   : Rename Files Recursively function
+# @Description   : Recursively rename files
 # @TODO          :
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-renameFilesRecursively() {
-  local FUNCTDIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$FUNCTDIR" ]]; then DIR="$PWD"; fi
-  if [[ -f "$FUNCTDIR/functions.bash" ]]; then source "$FUNCTDIR/functions.bash"; else
-    printf "\n\t\tCouldn't source the functions file\n"
-    exit 1
+__help() {
+  printf_custom 4 'usage: renameFilesRecursively "/home/user/my-files" "apple" "orange"'
+  printf_help 'Also uses env variables: SEARCH_DIR SEARCH REPLACE TYPE=file,dir'
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-  if [[ "$1" = "--help" ]]; then
-    printf_help 'usage: renameFilesRecursively "/home/user/my-files" "apple" "orange"'
-    printf_help 'Also uses env variables: SEARCH_DIR SEARCH REPLACE TYPE=file,dir'
-  fi
-
-  local NEW_FILENAME
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [[ "$1" = "--help" ]] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  local NEW_FILENAME exitCode
   local SEARCH_DIR="${1:-.}"
   local SEARCH_PATH="${1:-$SEARCH_PATH}"
   local SEARCH="${2:$SEARCH}"
   local REPLACE="${3:-}"
   local TYPE="${4:-$TYPE}"
-  local FINDTYPE=${TYPE:-file}
-
-  [ -z "$1" ] && [ -z "$SEARCH_PATH" ] && printf_green 'usage: renameFilesRecursively "/home/user/my-files" "apple" "orange"' && exit 1
-  [ -z "$2" ] && [ -z "$SEARCH" ] && printf_green 'usage: renameFilesRecursively "/home/user/my-files" "apple" "orange"' && exit 1
-
+  local FINDTYPE="${TYPE:-file}"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ -z "$1" ] && [ -z "$SEARCH_PATH" ] && __help
+  [ -z "$2" ] && [ -z "$SEARCH" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  move_file() { mv -f "${1:-$FILENAME}" "${2:-$NEW_FILENAME}" &>/dev/null && return 0 || return 1; }
+  fail_msg() { printf_red "Failed to move $FILENAME to $NEW_FILENAME" && exitCode+="1"; }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   if [ "$FINDTYPE" = d ] || [ "$FINDTYPE" = dir ]; then
     printf_green "Renaming all directories from $SEARCH to $REPLACE"
     find $SEARCH_PATH -type d -name "*$SEARCH*" -printf "%P\n" | while read -r FILENAME; do
       local NEW_FILENAME="${FILENAME//$SEARCH/$REPLACE}"
-      mv -f "$FILENAME" "$NEW_FILENAME" || printf_red "Failed to move $FILENAME to $NEW_FILENAME"
+      if move_file; then
+        [ -d "$NEW_FILENAME" ] || fail_msg
+      else
+        fail_msg
+      fi
     done
   else
     printf_green "Renaming all files from $SEARCH to $REPLACE"
     find $SEARCH_PATH -type f,l -name "*$SEARCH*" -printf "%P\n" | while read -r FILENAME; do
       local NEW_FILENAME="${FILENAME//$SEARCH/$REPLACE}"
-      mv -f "$FILENAME" "$NEW_FILENAME" || printf_red "Failed to move $FILENAME to $NEW_FILENAME"
+      if move_file; then
+        [ -e "$NEW_FILENAME" ] || fail_msg
+      else
+        fail_msg
+      fi
     done
   fi
-  #NEW_FILENAME="$(echo ${FILENAME} | sed -e "s/${SEARCH}/${REPLACE}/g")"
-
+  return ${exitCode:-$?}
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-renameFilesRecursively "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
diff --git a/bin/retry b/bin/retry
--- a/bin/retry
+++ b/bin/retry
@@ -1,49 +1,65 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="retry"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : retry
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : retry function
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211641-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : retry --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 16:41 EST
+# @File          : retry
+# @Description   : Keep retrying command
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-retry() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help "Usage: retry command"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: retry command"
-
-  typeset n=1
-  typeset max=5
-  typeset delay=15
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  typeset n=0
+  typeset max="${RETRY_MAX:-5}"
+  typeset delay="${RETRY_DELAY:-15}"
   while true; do
-    "$@" && break || {
+    eval "$@" && exitCode=0 && break || {
       if [[ $n -lt $max ]]; then
         ((n++))
-        echo "Command failed. Attempt $n/$max:"
+        printf_red "${1:-Command} failed. Attempt $n/$max:"
         sleep $delay
       else
-        printf_red "The command has failed after $n attempts."
+        printf_red "${1:-Command} has failed after $n attempts."
+        local exitCode+=1
+        break
       fi
     }
   done
+  return ${exitCode:-$?}
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-retry "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/rmd b/bin/rmd
--- a/bin/rmd
+++ b/bin/rmd
@@ -4,18 +4,19 @@
 PROG="rmd"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 030920212042-git
+##@Version       : 031120211651-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
 # @License       : WTFPL
 # @ReadME        : rmd --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Tuesday, Mar 09, 2021 20:42 EST
+# @Created       : Thursday, Mar 11, 2021 16:51 EST
 # @File          : rmd
 # @Description   : remove files and directories recursively
 # @TODO          :
@@ -23,19 +24,23 @@ HOME="${USER_HOME:-${HOME}}"
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-rmd() {
-  local DIR=${BASH_SOURCE%/*}
+__help(){
+  printf_help "Usage: rmd dir/file | delete a file or directory"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [ -f "$DIR/functions.bash" ]; then
     . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [ ! "$1" = "--help" ] || printf_help "Usage: rmd File or Directory to delete"
-
-  local files delete_dir delete_file delete_error_file
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __rm_file() { rm -Rf "${1:-$file}" &>/dev/null && exitCode+=0 || exitCode+=1; }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  local files delete_dir delete_file delete_error_file exitCode
   if [ $# -ne 0 ]; then
     local files="$@"
     for file in $files; do
@@ -47,22 +52,26 @@ rmd() {
       if [ -n "$file" ]; then
         if [ -d "$file" ]; then
           printf_green "Deleting folder and all files within: $file"
-          rm -Rf "$file" &>/dev/null
+          __rm_file "$file"
         elif [ -e "$file" ]; then
           printf_green "Deleting the file: $file"
-          rm -Rf "$file" &>/dev/null
+          __rm_file "$file" &>/dev/null
         else
           printf_red "Failed to delete non-existant file/folder: $file"
+          local exitCode=1
         fi
       fi
     done
   else
     printf_red "Must provide path to file or folder for deletion"
+    return 1
   fi
+  return ${exitCode:-$?}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-rmd "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
diff --git a/bin/rr b/bin/rr
--- a/bin/rr
+++ b/bin/rr
@@ -1,36 +1,60 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="rr"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : rr
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : terminal rickroll
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211659-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : rr --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 16:59 EST
+# @File          : rr
+# @Description   : terminal rickroll
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-rr() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
-  else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
-  fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: rr | get rickrolled"
-
-  curl -LSs https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash
+__help() {
+  printf_help "Usage: rr | get rickrolled in the terminal"
 }
-
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if am_i_online; then
+    rr="$(curl -q --fail -LSs https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh 2>/dev/null || return 1)"
+    if [ -n "$rr" ]; then
+      $rr 2>/dev/null
+    else
+      printf_red "An error has occurred while fetching the script"
+      return 1
+    fi
+  else
+    printf_red "Never gonna give you up"
+    return 1
+  fi
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-rr "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/set_new_version b/bin/set_new_version
--- a/bin/set_new_version
+++ b/bin/set_new_version
@@ -1,39 +1,52 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="set_new_version"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : set_new_version
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Set new version recursively
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211717-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : set_new_version --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 17:17 EST
+# @File          : set_new_version
+# @Description   : Set new version recursively
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-main() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
-  else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
-  fi
-
-  [ ! "$1" = "--help" ] || printf_help "Usage: set_new_version"
-
-  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  setver="$(date +"%m%d%Y%H%M-git")"
-  printf_green "Changing the version to $setver in $1"
-  find "$1" -type f -exec sed -i "s/##@Version.*/##@Version     : $setver/g" {} \;
+__help() {
+  printf_help "Usage: set_new_version dir  |  set_new_version ~/Projects/github"
 }
-
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  local search_dir="${1:-$PWD}"
+  local setver="$(date +"%m%d%Y%H%M-git")"
+  printf_green "Changing the version to $setver in $search_dir"
+    find -L "$search_dir" -type f,l -exec sed -i --follow-symlinks 's/^##@Version.*/##@Version       : '$setver'/g' {} \; 2>/dev/null
+  return $?
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
diff --git a/bin/show_wifi_clients b/bin/show_wifi_clients
--- a/bin/show_wifi_clients
+++ b/bin/show_wifi_clients
@@ -1,49 +1,72 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="show_wifi_clients"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : show_wifi_clients
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : shows connected stations in hotspot mode
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211747-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : show_wifi_clients --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 17:47 EST
+# @File          : show_wifi_clients
+# @Description   : shows connected stations in hotspot mode
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-show_wifi_clients() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  printf_help "shows connected stations in hotspot mode"
+}
+main() {
+  local DIR="${BASH_SOURCE%/*}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help "shows connected stations in hotspot mode"
-
-  printf_green "# All connected wifi devices, with IP address,"
-  printf_green "# hostname (if available), and MAC address."
-  printf_red "# %-20s %-30s %-20s" "IP address" "lease name" "MAC address"
-  leasefile=/var/lib/misc/dnsmasq.leases
-  for interface in $(iw dev | grep Interface | cut -f 2 -s -d" "); do
-    maclist=$(iw dev $interface station dump | grep Station | cut -f 2 -s -d" ")
-    for mac in $maclist; do
-      ip="UNKN"
-      host=""
-      ip=$(cat $leasefile | cut -f 2,3,4 -s -d" " | grep $mac | cut -f 2 -s -d" ")
-      host=$(cat $leasefile | cut -f 2,3,4 -s -d" " | grep $mac | cut -f 3 -s -d" ")
-      printf "%-20s %-30s %-20s" $ip $host $mac
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && printf_help "shows connected stations in hotspot mode"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if [ -f "/etc/dnsmasq.conf" ]; then
+    leasefileconf="$(grep 'dhcp-leasefile=' /etc/dnsmasq.conf | sed 's/#//g;s#dhcp-leasefile=##g' | grep '^' || return 1)"
+  fi
+  leasefile="${leasefileconf:-/var/lib/misc/dnsmasq.leases}"
+  dnsmasqbin="$(command -v dnsmasq 2>/dev/null)"
+  if [ -f "$leasefile" ] && [ -f "$dnsmasqbin" ]; then
+    printf_green "# All connected wifi devices, with IP address,"
+    printf_green "# hostname (if available), and MAC address."
+    for interface in $(iw dev | grep Interface | cut -f 2 -s -d" "); do
+      maclist=$(iw dev $interface station dump | grep Station | cut -f 2 -s -d" ")
+      for mac in $maclist; do
+        ip="UNKN"
+        host=""
+        ip=$(cat $leasefile | cut -f 2,3,4 -s -d" " | grep $mac | cut -f 2 -s -d" ")
+        host=$(cat $leasefile | cut -f 2,3,4 -s -d" " | grep $mac | cut -f 3 -s -d" ")
+        printf "%-20s %-30s %-20s" $ip $host $mac | printf_readline "5"
+      done
     done
-  done
+  else
+    printf_red "Make sure dnsmasq is installed and running!"
+    return 1
+  fi
+  return $?
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-show_wifi_clients "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/showclip b/bin/showclip
--- a/bin/showclip
+++ b/bin/showclip
@@ -1,54 +1,63 @@
-#!/bin/sh
 #!/usr/bin/env bash
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 PROG="showclip"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 031120210349-git
+##@Version       : 031120211744-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
 # @License       : WTFPL
 # @ReadME        : showclip --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Thursday, Mar 11, 2021 03:49 EST
+# @Created       : Thursday, Mar 11, 2021 17:44 EST
 # @File          : showclip
 # @Description   : Show clipboard
 # @TODO          :
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# main function
 __help() {
   printf_help "Usage: showclip | show clipboard contents"
 }
 main() {
-  local SRC_DIR="${BASH_SOURCE%/*}"
   local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
     . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || __help
-
-  clip=$(xclip -o -selection clipboard)
-  prim=$(xclip -o -selection primary)
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  clip=$(xclip -o -selection clipboard 2>/dev/null || return 1)
+  prim=$(xclip -o -selection primary 2>/dev/null || return 1)
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   if [ -n "$clip" ] && [ "$clip" = "$prim" ]; then
     notifications "Clipboard:" "$clip"
+  elif [ -n "$clip" ] &&  [ -n "$prim" ]; then
+    notifications "Clipboard:" "$clip"
+    notifications "Primary:" "$prim"
+  elif [ -n "$clip" ]; then
+    notifications "Clipboard:" "$clip"
+  elif [ -n "$prim" ]; then
+    notifications "Primary:" "$prim"
   else
-    [ -n "$clip" ] && notifications "Clipboard:" "$clip"
-    [ -n "$prim" ] && notifications "Primary:" "$prim"
+    notifications "Clipboard:" "There is nothing in your clipboard"
+    return 1
   fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
diff --git a/bin/social_post b/bin/social_post
--- a/bin/social_post
+++ b/bin/social_post
@@ -1,37 +1,52 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="social_post"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : social_post
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Send a post to both mastodon and twitter
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211822-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : social_post --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 18:22 EST
+# @File          : social_post
+# @Description   : Send a post to both mastodon and twitterw
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-social_post() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+__help() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
   if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+    . "$DIR/functions.bash"
   else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  [ ! "$1" = "--help" ] || printf_help 'Usage: social_post "Message to post"'
-
-  tweet "$@" >/dev/null 2>&1
-  mastodon "$@" >/dev/null 2>&1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  tweet "$@" &>/dev/null && exitCode+=0 || exitCode+=1
+  mastodon "$@" &>/dev/null && exitCode+=0 || exitCode+=1
+  return ${exitCode:$?}
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-social_post "$@"
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/tweet b/bin/tweet
--- a/bin/tweet
+++ b/bin/tweet
@@ -1,36 +1,50 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="tweet"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : tweet
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : post to twitter
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211840-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : tweet --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 18:40 EST
+# @File          : tweet
+# @Description   : post to twitter
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-tweet() {
-  DIR="${BASH_SOURCE%/*}"
-  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
-  else
-    echo "\t\tCouldn't source the functions file"
-    exit 1
-  fi
-
-  [ ! "$1" = "--help" ] || printf_help 'Usage: tweet "messagetoPost"'
-
-  twitter set "$@"
+__help() {
+  printf_help 'Usage: tweet "messagetoPost"'
 }
-
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  twitter set "$@" && exitCode=0 || exitCode=1
+  return ${exitCode:-$?}
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
 tweet "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
diff --git a/bin/xephyr b/bin/xephyr
--- a/bin/xephyr
+++ b/bin/xephyr
@@ -1,47 +1,71 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="xephyr"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : xephyr
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : xephyr
-#
+#set opts
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031120211857-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : xephyr --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 18:57 EST
+# @File          : xephyr
+# @Description   : xephyr
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
-
-DIR="${BASH_SOURCE%/*}"
-if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
-if [[ -f "$DIR/functions.bash" ]]; then
-  source "$DIR/functions.bash"
-else
-  echo "\t\tCouldn't source the functions file"
-  exit 1
-fi
-
-[ ! "$1" = "--help" ] || printf_help "Usage xephyr"
-
-declare -a args="$@"
-if cmd_exists Xephyr || cmd_exists xephyr; then
-  if [ ! -z "$DISPLAY_LOW_DENSITY" ]; then
-    DISPLAY="$DISPLAY_LOW_DENSITY" RESOLUTION="$(xrandr --current | grep '*' | uniq | awk '{print $1}')"
+__help() {
+  printf_help "Usage: xephyr commands  |  xephyr bash"
+}
+main() {
+  local DIR="${SRC_DIR:-$PWD}"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
   else
-    DISPLAY="$DISPLAY RESOLUTION"="$(xrandr --current | grep '*' | uniq | awk '{print $1}')"
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-
-  if ! pidof Xephyr >/dev/null 2>&1; then
-    Xephyr -br -ac -noreset -screen "$RESOLUTION" :9 >/dev/null 2>&1 &
-    sleep 3
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  local -a args="$@" && shift $#
+  local PATH="/usr/bin:/usr/sbin"
+  local xephyr="$(command -v xephyr || command -v Xephyr || return 1)"
+  if [ -f "$xephyr"] ; then
+    if [ -n "$DISPLAY_LOW_DENSITY" ]; then
+      local DISPLAY="$DISPLAY_LOW_DENSITY"
+      local RESOLUTION="$(xrandr --current | grep '*' | uniq | awk '{print $1}')"
+    else
+      local DISPLAY="$DISPLAY"
+      local RESOLUTION="$(xrandr --current | grep '*' | uniq | awk '{print $1}')"
+    fi
+    if ! pidof $xephyr >/dev/null 2>&1; then
+      $xephyr -br -ac -noreset -screen "$RESOLUTION" :9 >/dev/null 2>&1 &
+      exitCode+=$?
+      sleep 3
+    fi
+    DISPLAY=:9 "$args" >/dev/null 2>&1
+    exitCode=+$?
+  else
+    printf_red "xephyr doesn't seem to be installed"
+    exitCode=1
   fi
-  DISPLAY=:9 "$args" >/dev/null 2>&1
-fi
-
+  return ${exitCode:-$?}
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
