🏠🐜❗ Minor Fixes ❗🐜🏠

diff --git a/bin/append_path b/bin/append_path
--- a/bin/append_path
+++ b/bin/append_path
@@ -16,7 +16,17 @@ USER="${SUDO_USER:-${USER}}"
 # Main function
 
 append_path() {
-  [ ! "$1" = "--help" ] || printf_help "Usage: append_path path"
+  DIR="${BASH_SOURCE%/*}"
+  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+  if [[ -f "$DIR/functions.bash" ]]; then
+    source "$DIR/functions.bash"
+  else
+    echo -e "\t\tCouldn't source the functions file"
+    exit 1
+  fi
+
+  [ ! "$1" = "--help" ] || printf_help "Usage: append_path path    |    appends directory to path"
+
   case ":$PATH:" in
   *:"$1":*) ;;
 
diff --git a/bin/checkup b/bin/checkup
--- a/bin/checkup
+++ b/bin/checkup
@@ -16,7 +16,18 @@ USER="${SUDO_USER:-${USER}}"
 # Main function
 
 checkup() {
-  ping -q -c 1 1.1.1.1 >/dev/null || exit
+  DIR="${BASH_SOURCE%/*}"
+  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+  if [[ -f "$DIR/functions.bash" ]]; then
+    source "$DIR/functions.bash"
+  else
+    echo -e "\t\tCouldn't source the functions file"
+    exit 1
+  fi
+
+  [ ! "$1" = "--help" ] || printf_help "Usage: checkup    |   Check for pacman updates"
+
+  ping -q -c 1 1.1.1.1 >/dev/null || exit 1
 
   if cmd_exists pacman; then
     notify-send "📦 Repository Sync" "Checking for package updates..."
diff --git a/bin/linkhandler b/bin/linkhandler
--- a/bin/linkhandler
+++ b/bin/linkhandler
@@ -7,26 +7,42 @@
 # otherwise it opens link in browser.
 
 # If no url given. Opens browser. For using script as $BROWSER.
-[ -z "$1" ] && {
-  "$BROWSER"
-  exit
+
+main() {
+  DIR="${BASH_SOURCE%/*}"
+  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+  if [[ -f "$DIR/functions.bash" ]]; then
+    source "$DIR/functions.bash"
+  else
+    echo "\t\tCouldn't source the functions file"
+    exit 1
+  fi
+
+  [ ! "$1" = "--help" ] || printf_help "Usage: linkhander pathtofile or url"
+
+  [ -z "$1" ] && {
+    "$BROWSER"
+    exit
+  }
+
+  case "$1" in
+  *mkv | *webm | *mp4 | *youtube.com/watch* | *youtube.com/playlist* | *youtu.be* | *hooktube.com* | *bitchute.com*)
+    setsid mpv --input-ipc-server=/tmp/mpvsoc$(date +%s) -quiet "$1" >/dev/null 2>&1 &
+    ;;
+  *png | *jpg | *jpe | *jpeg | *gif)
+    curl -sL "$1" >"/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")" >/dev/null 2>&1 &
+    ;;
+  *mp3 | *flac | *opus | *mp3?source*)
+    setsid tsp curl -LO "$1" >/dev/null 2>&1 &
+    ;;
+  *)
+    if [ -f "$1" ]; then
+      "$TERMINAL" -e "$EDITOR $1"
+    else
+      setsid "$BROWSER" "$1" >/dev/null 2>&1 &
+    fi
+    ;;
+  esac
 }
 
-case "$1" in
-*mkv | *webm | *mp4 | *youtube.com/watch* | *youtube.com/playlist* | *youtu.be* | *hooktube.com* | *bitchute.com*)
-  setsid mpv --input-ipc-server=/tmp/mpvsoc$(date +%s) -quiet "$1" >/dev/null 2>&1 &
-  ;;
-*png | *jpg | *jpe | *jpeg | *gif)
-  curl -sL "$1" >"/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")" >/dev/null 2>&1 &
-  ;;
-*mp3 | *flac | *opus | *mp3?source*)
-  setsid tsp curl -LO "$1" >/dev/null 2>&1 &
-  ;;
-*)
-  if [ -f "$1" ]; then
-    "$TERMINAL" -e "$EDITOR $1"
-  else
-    setsid "$BROWSER" "$1" >/dev/null 2>&1 &
-  fi
-  ;;
-esac
+main "$@"
diff --git a/bin/pasteit b/bin/pasteit
--- a/bin/pasteit
+++ b/bin/pasteit
@@ -16,39 +16,39 @@ USER="${SUDO_USER:-${USER}}"
 
 # Set functions
 
-DIR="${BASH_SOURCE%/*}"
-if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+main() {
+  DIR="${BASH_SOURCE%/*}"
+  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
   if [[ -f "$DIR/functions.bash" ]]; then
     source "$DIR/functions.bash"
   else
     echo "\t\tCouldn't source the functions file"
     exit 1
-fi
+  fi
 
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-[ "$1" = "--version" ] && get_app_info "$APPNAME"
-[ "$1" = "--help " ] && printf_exit "Pastes from STDIN or file from commandline argument to Stikked pastebin"
+  [ "$1" = "--help " ] && printf_exit "Pastes from STDIN or file from commandline argument to Stikked pastebin"
 
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-set -e
-PROGRAM=${0##*/}
+  set -e
+  PROGRAM=${0##*/}
 
-# can be overriden from env
-PASTE_URL="${PRIVATE_PASTEBIN_URL:-https://casjay.cc}/api/create"
-PASTE_APIKEY="${PRIVATE_PASTEBIN_APIKEY:-apikey}"
+  # can be overriden from env
+  PASTE_URL="${PRIVATE_PASTEBIN_URL:-https://casjay.cc}/api/create"
+  PASTE_APIKEY="${PRIVATE_PASTEBIN_APIKEY:-apikey}"
 
-# filter url for printing (remove password)
-print_url() {
-  local url="$1"
-  echo "$url" | sed -e 's;://[^@]*@;://;'
-}
+  # filter url for printing (remove password)
+  print_url() {
+    local url="$1"
+    echo "$url" | sed -e 's;://[^@]*@;://;'
+  }
 
-# paste. take input from stdin
-pastebin() {
-  # show params
-  sed -e '/^$/d' >&2 <<-EOF
+  # paste. take input from stdin
+  pastebin() {
+    # show params
+    sed -e '/^$/d' >&2 <<-EOF
 		${PASTE_APIKEY+apikey: "$PASTE_APIKEY"}
 		${title+title: "$title"}
 		${name+name: "$name"}
@@ -58,22 +58,22 @@ pastebin() {
 		${reply+reply: "$reply"}
 	EOF
 
-  # do paste
-  curl "$PASTE_URL${PASTE_APIKEY+?apikey=${PASTE_APIKEY}}" \
-    ${title+-F title="$title"} \
-    ${name+-F name="$name"} \
-    ${private+-F private="$private"} \
-    ${language+-F lang="$language"} \
-    ${expire+-F expire="$expire"} \
-    ${reply+-F reply="$reply"} \
-    -F 'text=<-'
-}
+    # do paste
+    curl "$PASTE_URL${PASTE_APIKEY+?apikey=${PASTE_APIKEY}}" \
+      ${title+-F title="$title"} \
+      ${name+-F name="$name"} \
+      ${private+-F private="$private"} \
+      ${language+-F lang="$language"} \
+      ${expire+-F expire="$expire"} \
+      ${reply+-F reply="$reply"} \
+      -F 'text=<-'
+  }
 
-# try to resolve mime-type to language
-mime_to_lang() {
-  local mime="$1"
+  # try to resolve mime-type to language
+  mime_to_lang() {
+    local mime="$1"
 
-  awk -F ':' -vm="$mime" 'm==$1 {print $2}' <<-EOF
+    awk -F ':' -vm="$mime" 'm==$1 {print $2}' <<-EOF
 	application/javascript:javascript
 	application/xml:xml
 	text/html:html5
@@ -86,18 +86,18 @@ mime_to_lang() {
 	text/x-ruby:ruby
 	text/x-shellscript:bash
 	EOF
-}
+  }
 
-# detect filetype. outputs nothing if no file binary or no detected
-detect_mimetype() {
-  local file="$1" out
+  # detect filetype. outputs nothing if no file binary or no detected
+  detect_mimetype() {
+    local file="$1" out
 
-  out=$(file -L --mime-type "$file" 2>/dev/null || :)
-  echo "${out#*: }"
-}
+    out=$(file -L --mime-type "$file" 2>/dev/null || :)
+    echo "${out#*: }"
+  }
 
-usage() {
-  echo "Usage: $PROGRAM [options] < [input_file]
+  usage() {
+    echo "Usage: $PROGRAM [options] < [input_file]
 
 Options:
   -a, --apikey    API key for the server
@@ -108,99 +108,99 @@ Options:
   -e, --expire    paste expiration in minutes
   -r, --reply     reply to existing paste
 "
-}
+  }
 
-set_defaults() {
-  unset title
-  unset private
-  unset language
-  unset expire
-  unset reply
+  set_defaults() {
+    unset title
+    unset private
+    unset language
+    unset expire
+    unset reply
 
-  # default to user
-  name=${SUDO_USER:-$USER}
-}
+    # default to user
+    name=${SUDO_USER:-$USER}
+  }
 
-set_defaults
+  set_defaults
 
-# parse command line args
-t=$(getopt -o h,t:,n:,p,l:,e:,r:,b:,a: --long help,title:,name:,private,language:,expire:,reply:,apikey: -n "$PROGRAM" -- "$@")
-eval set -- "$t"
+  # parse command line args
+  t=$(getopt -o h,t:,n:,p,l:,e:,r:,b:,a: --long help,title:,name:,private,language:,expire:,reply:,apikey: -n "$PROGRAM" -- "$@")
+  eval set -- "$t"
 
-while :; do
-  case "$1" in
-  -h | --help)
-    usage
-    exit 0
-    ;;
-  -t | --title)
+  while :; do
+    case "$1" in
+    -h | --help)
+      usage
+      exit 0
+      ;;
+    -t | --title)
+      shift
+      title="$1"
+      ;;
+    -n | --name)
+      shift
+      name="$1"
+      ;;
+    -p | --private)
+      private=1
+      ;;
+    -l | --language)
+      shift
+      language="$1"
+      ;;
+    -e | --expire)
+      shift
+      expire="$1"
+      ;;
+    -r | --reply)
+      shift
+      reply="$1"
+      ;;
+    -b)
+      shift
+      PASTE_URL="$1"
+      ;;
+    -a | --apikey)
+      shift
+      PASTE_APIKEY="$1"
+      ;;
+    --)
+      shift
+      break
+      ;;
+    *)
+      echo >&2 "$PROGRAM: Internal error: [$1] not recognized!"
+      exit 1
+      ;;
+    esac
     shift
-    title="$1"
-    ;;
-  -n | --name)
-    shift
-    name="$1"
-    ;;
-  -p | --private)
-    private=1
-    ;;
-  -l | --language)
-    shift
-    language="$1"
-    ;;
-  -e | --expire)
-    shift
-    expire="$1"
-    ;;
-  -r | --reply)
-    shift
-    reply="$1"
-    ;;
-  -b)
-    shift
-    PASTE_URL="$1"
-    ;;
-  -a | --apikey)
-    shift
-    PASTE_APIKEY="$1"
-    ;;
-  --)
-    shift
-    break
-    ;;
-  *)
-    echo >&2 "$PROGRAM: Internal error: [$1] not recognized!"
-    exit 1
-    ;;
-  esac
-  shift
-done
+  done
 
-printf "Paste endpoint: %s\n" "$(print_url "$PASTE_URL")"
+  printf "Paste endpoint: %s\n" "$(print_url "$PASTE_URL")"
 
-# if we have more commandline arguments, set these as title
-if [ "${title+set}" != "set" ]; then
-  title="$*"
-fi
-
-# set language from first filename
-if [ -n "$1" ] && [ "${language+set}" != "set" ]; then
-  mime=$(detect_mimetype "$1")
-
-  if [ -n "$mime" ]; then
-    language=$(mime_to_lang "$mime")
+  # if we have more commandline arguments, set these as title
+  if [ "${title+set}" != "set" ]; then
+    title="$*"
   fi
-fi
 
-# take filenames from commandline, or from stdin
-if [ $# -gt 0 ]; then
-  paste=$(cat "$@")
-else
-  paste=$(cat)
-fi
+  # set language from first filename
+  if [ -n "$1" ] && [ "${language+set}" != "set" ]; then
+    mime=$(detect_mimetype "$1")
 
-printf "%s" "$paste" | pastebin
+    if [ -n "$mime" ]; then
+      language=$(mime_to_lang "$mime")
+    fi
+  fi
 
+  # take filenames from commandline, or from stdin
+  if [ $# -gt 0 ]; then
+    paste=$(cat "$@")
+  else
+    paste=$(cat)
+  fi
+
+  printf "%s" "$paste" | pastebin
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
+main "$@"
 # end
diff --git a/bin/pauseallmpv b/bin/pauseallmpv
--- a/bin/pauseallmpv
+++ b/bin/pauseallmpv
@@ -5,6 +5,21 @@
 # every single one of them with one command! This is bound to super + shift + p
 # (with other things) by default and is used in some other places.
 
-for i in $(ls /tmp/mpvsoc*); do
-	echo '{ "command": ["set_property", "pause", true] }' | socat - $i
-done
+main() {
+  DIR="${BASH_SOURCE%/*}"
+  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+  if [[ -f "$DIR/functions.bash" ]]; then
+    source "$DIR/functions.bash"
+  else
+    echo "\t\tCouldn't source the functions file"
+    exit 1
+  fi
+
+  [ ! "$1" = "--help" ] || printf_help "Usage: pauseallmpv    |    pause mpv"
+
+  for i in $(ls /tmp/mpvsoc*); do
+    echo '{ "command": ["set_property", "pause", true] }' | socat - $i
+  done
+}
+
+main "$@"
diff --git a/bin/prompt b/bin/prompt
--- a/bin/prompt
+++ b/bin/prompt
@@ -5,4 +5,19 @@
 # For example:
 # `./prompt "Do you want to shutdown?" "shutdown -h now"`
 
-[ "$(printf "No\\nYes" | dmenu -i -p "$1" -nb darkred -sb red -sf white -nf gray)" = "Yes" ] && $2
+main() {
+  DIR="${BASH_SOURCE%/*}"
+  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+  if [[ -f "$DIR/functions.bash" ]]; then
+    source "$DIR/functions.bash"
+  else
+    echo "\t\tCouldn't source the functions file"
+    exit 1
+  fi
+
+  [ ! "$1" = "--help" ] || printf_help "Usage: prompt message action    |    custom dmenu prompt"
+
+  [ "$(printf "No\\nYes" | dmenu -i -p "$1" -nb darkred -sb red -sf white -nf gray)" = "Yes" ] && $2
+}
+
+main "$@"
diff --git a/bin/randomwallpaper b/bin/randomwallpaper
--- a/bin/randomwallpaper
+++ b/bin/randomwallpaper
@@ -15,6 +15,17 @@ USER="${SUDO_USER:-${USER}}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
 
+DIR="${BASH_SOURCE%/*}"
+if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+if [[ -f "$DIR/functions.bash" ]]; then
+  source "$DIR/functions.bash"
+else
+  echo "\t\tCouldn't source the functions file"
+  exit 1
+fi
+
+[ ! "$1" = "--help" ] || printf_help "Usage: randomwallpaper"
+
 send_notify_wp() {
   command -v notify-send >/dev/null 2>&1 &&
     notify-send "Wallpaper Changer" "Wallpaper has been changed to $RAND" ||
diff --git a/bin/set_new_version b/bin/set_new_version
--- a/bin/set_new_version
+++ b/bin/set_new_version
@@ -15,19 +15,24 @@ USER="${SUDO_USER:-${USER}}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
 
-__help() {
-  Usage: $APPNAME "folder"
+main() {
+  DIR="${BASH_SOURCE%/*}"
+  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+  if [[ -f "$DIR/functions.bash" ]]; then
+    source "$DIR/functions.bash"
+  else
+    echo "\t\tCouldn't source the functions file"
+    exit 1
+  fi
+
+  [ ! "$1" = "--help" ] || printf_help "Usage: set_new_version"
+
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+  find "$1" -type f -exec sed -i "s/##@Version.*/##@Version     : $(setver)/g" {} \;
 }
 
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-[ "$1" = "--help" ] && __help
-[ -z "$1" ] && _help
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-find "$1" -type f -exec sed -i "s/##@Version.*/##@Version     : $(setver)/g" {} \;
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit #?
 # end
diff --git a/bin/showclip b/bin/showclip
--- a/bin/showclip
+++ b/bin/showclip
@@ -2,8 +2,23 @@
 
 # Display contents of selection.
 
-clip=$(xclip -o -selection clipboard)
-prim=$(xclip -o -selection primary)
+main() {
+  DIR="${BASH_SOURCE%/*}"
+  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+  if [[ -f "$DIR/functions.bash" ]]; then
+    source "$DIR/functions.bash"
+  else
+    echo "\t\tCouldn't source the functions file"
+    exit 1
+  fi
 
-[ -n "$clip" ] && notify-send "Clipboard:" "$clip"
-[ -n "$prim" ] && notify-send "Primary:" "$prim"
+  [ ! "$1" = "--help" ] || printf_help "Usage: showclip"
+
+  clip=$(xclip -o -selection clipboard)
+  prim=$(xclip -o -selection primary)
+
+  [ -n "$clip" ] && notify-send "Clipboard:" "$clip"
+  [ -n "$prim" ] && notify-send "Primary:" "$prim"
+}
+
+main "$@"
