🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/checkup b/bin/checkup
--- a/bin/checkup
+++ b/bin/checkup
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
-checkup() {
+checkup_main() {
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  PROG="checkup"
+  PROG="$(basename $0)"
+  VERSION="202103230741-git"
   USER="${SUDO_USER:-${USER}}"
   HOME="${USER_HOME:-${HOME}}"
   SRC_DIR="${BASH_SOURCE%/*}"
@@ -9,63 +10,170 @@ checkup() {
   #set opts
 
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  ##@Version       : 031120210423-git
+  ##@Version       : 202103230741-git
   # @Author        : Jason Hempstead
   # @Contact       : jason@casjaysdev.com
   # @License       : WTFPL
   # @ReadME        : checkup --help
   # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-  # @Created       : Thursday, Mar 11, 2021 04:23 EST
+  # @Created       : Tuesday, Mar 23, 2021 07:41 EDT
   # @File          : checkup
   # @Description   : check for system updates
   # @TODO          : make compatible with all package managers
   # @Other         : used primarily by i3
   # @Resource      :
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  # Main function
-  __version() { app_version; }
-  __help() {
-    app_help "Usage: checkup" \
-      "-v, --version          -  display version" \
-      "-h, --help             -  display help"
-  }
-  if [ -f "$SRC_DIR/functions.bash" ]; then local DIR="$SRC_DIR"; else local DIR="$HOME/.local/bin"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    . "$DIR/functions.bash"
+  # Main function file
+  if [ -f "$SRC_DIR/functions.bash" ]; then
+    FUNCTIONS_DIR="$SRC_DIR"
+    . "$FUNCTIONS_DIR/functions.bash"
+  elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+    FUNCTIONS_DIR="$HOME/.local/bin"
+    . "$FUNCTIONS_DIR/functions.bash"
   else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
     return 1
   fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  case $1 in
-  -v | --version) __version ;;
-  -h | --help) __help ;;
-  esac
-
+  # helper functions - See github.com/dfmgr/misc/bin/functions.bash
+  __notify() { [ "$CHECKUP_NOTIFICATIONS_ENABLE" = "yes" ] && notifications "$1" "$2"; }
+  __version() { app_version; }
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  __pacman() { am_i_online && sudo pacman "$@" || return 1; }
-  if [ "$(command -v pacman)" ]; then
-    notifications "📦 Repository Sync" "Checking for package updates..."
-    if __pacman -Syyuw --noconfirm; then
-      if __pacman -Qu | grep -v "\[ignored\]"; then
-        notifications "🎁 Repository Sync" "Updates available."
+  __help() {
+    app_help "4" "Usage: checkup  -  checkup --version" \
+      "-c, --config           -  create config file" \
+      "-a, --all              -  show all options" \
+      "-l, --list             -  used by completions" \
+      "-v, --version          -  display version" \
+      "-h, --help             -  display help"
+    exit $?
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __gen_config() {
+    printf_green "Generating the config file in"
+    printf_green "$CHECKUP_CONFIG_DIR/$CHECKUP_CONFIG_FILE"
+    [ -d "$CHECKUP_CONFIG_DIR" ] || mkdir -p "$CHECKUP_CONFIG_DIR"
+    [ -f "$CHECKUP_CONFIG_DIR/$CHECKUP_CONFIG_FILE" ] &&
+      cp -Rf "$CHECKUP_CONFIG_DIR/$CHECKUP_CONFIG_FILE" "$CHECKUP_CONFIG_DIR/$CHECKUP_CONFIG_FILE.$$"
+    cat <<EOF >"$CHECKUP_CONFIG_DIR/$CHECKUP_CONFIG_FILE"
+# Settings for checkup
+CHECKUP_NOTIFICATIONS_NAME="CheckUP"
+CHECKUP_NOTIFICATIONS_ENABLE="${CHECKUP_NOTIFICATIONS_ENABLE=yes}"
+CHECKUP_NOTIFICATIONS_SYNC_NAME="📦 \$CHECKUP_NOTIFICATIONS_NAME"
+CHECKUP_NOTIFICATIONS_NOUPDATES_NAME="📦 \$CHECKUP_NOTIFICATIONS_NAME"
+CHECKUP_NOTIFICATIONS_UPDATES_NAME="🎁 \$CHECKUP_NOTIFICATIONS_NAME"
+CHECKUP_NOTIFICATIONS_ERROR_NAME="📦 \$CHECKUP_NOTIFICATIONS_NAME"
+CHECKUP_NOTIFICATIONS_SYNC_MESG="Checking for package updates..."
+CHECKUP_NOTIFICATIONS_NOUPDATES_MESG="No updates available"
+CHECKUP_NOTIFICATIONS_UPDATES_MESG="Updates available."
+CHECKUP_NOTIFICATIONS_ERROR_MESG="Error downloading updates."
+NOTIFY_CLIENT_ICON="software"
+NOTIFY_CLIENT_NAME="\$CHECKUP_NOTIFICATIONS_NAME"
+EOF
+    if [ -f "$CHECKUP_CONFIG_DIR/$CHECKUP_CONFIG_FILE" ]; then
+      printf_green "Your config file for checkup has been created"
+      true
+    else
+      printf_red "Failed to create the config file"
+      false
+    fi
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Defaults
+  local exitCode= CHECKUP_CONFIG_FILE= CHECKUP_CONFIG_DIR= CHECKUP_OPTIONS_DIR=
+  local CHECKUP_CONFIG_FILE="settings.conf"
+  local CHECKUP_CONFIG_DIR="$HOME/.config/misc/configs/checkup"
+  local CHECKUP_OPTIONS_DIR="$HOME/.local/share/misc/options/checkup"
+  local CHECKUP_NOTIFICATIONS_NAME="CheckUP"
+  local CHECKUP_NOTIFICATIONS_ENABLE="${CHECKUP_NOTIFICATIONS_ENABLE=yes}"
+  local CHECKUP_NOTIFICATIONS_SYNC_NAME="📦 $CHECKUP_NOTIFICATIONS_NAME"
+  local CHECKUP_NOTIFICATIONS_NOUPDATES_NAME="📦 $CHECKUP_NOTIFICATIONS_NAME"
+  local CHECKUP_NOTIFICATIONS_UPDATES_NAME="🎁 $CHECKUP_NOTIFICATIONS_NAME"
+  local CHECKUP_NOTIFICATIONS_ERROR_NAME="📦 $CHECKUP_NOTIFICATIONS_NAME"
+  local CHECKUP_NOTIFICATIONS_SYNC_MESG="Checking for package updates..."
+  local CHECKUP_NOTIFICATIONS_NOUPDATES_MESG="No updates available"
+  local CHECKUP_NOTIFICATIONS_UPDATES_MESG="Updates available."
+  local CHECKUP_NOTIFICATIONS_ERROR_MESG="Error downloading updates."
+  export NOTIFY_CLIENT_ICON="software"
+  export NOTIFY_CLIENT_NAME="$CHECKUP_NOTIFICATIONS_NAME"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Argument/Option settings
+  local SETARGS="${*}"
+  local SHORTOPTS="a,l,c,v,h"
+  local LONGOPTS="all,list,config,version,help"
+  local ARRAY=""
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Generate Files
+  [ -f "$CHECKUP_OPTIONS_DIR/options" ] || __list_options "$CHECKUP_OPTIONS_DIR" "$ARRAY" &>/dev/null
+  [ -f "$CHECKUP_OPTIONS_DIR/array" ] || __list_array "$CHECKUP_OPTIONS_DIR" &>/dev/null
+  [ -f "$CHECKUP_CONFIG_DIR/$CHECKUP_CONFIG_FILE" ] || __gen_config &>/dev/null
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Import config
+  [ -f "$CHECKUP_CONFIG_DIR/$CHECKUP_CONFIG_FILE" ] && . "$CHECKUP_CONFIG_DIR/$CHECKUP_CONFIG_FILE"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  local setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -n "$PROG" -- "$@" 2>/dev/null)
+  eval set -- "$setopts" 2>/dev/null
+  while :; do
+    case $1 in
+    -a | --all)
+      __list_options "$CHECKUP_OPTIONS_DIR" "$ARRAY"
+      exit $?
+      ;;
+    -l | --list)
+      __list_array "$CHECKUP_OPTIONS_DIR"
+      exit $?
+      ;;
+    -v | --version)
+      __version
+      exit $?
+      ;;
+    -h | --help)
+      __help
+      exit $?
+      ;;
+    -c | --config)
+      __gen_config
+      exit $?
+      ;;
+    --)
+      shift 1
+      break
+      ;;
+      #*) break ;;
+    esac
+    shift
+  done
+  set -- "$SETARGS"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Check for required applications
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  if [ "$(command -v pkmgr)" ]; then
+    notifications "$CHECKUP_NOTIFICATIONS_SYNC_NAME" "$CHECKUP_NOTIFICATIONS_SYNC_MESG"
+    if pkmgr check; then
+      if [ "$(pkmgr check)" = 0 ]; then
+        __notify "$CHECKUP_NOTIFICATIONS_NOUPDATES_NAME" "$CHECKUP_NOTIFICATIONS_NOUPDATES_MESG"
       else
-        notifications "📦 Repository Sync" "Sync complete. No new packages for update."
+        __notify "$CHECKUP_NOTIFICATIONS_UPDATES_NAME" "$CHECKUP_NOTIFICATIONS_UPDATES_MESG"
       fi
       local exitCode=0
     else
-      notifications "Error downloading updates."
+      __notify "$CHECKUP_NOTIFICATIONS_ERROR_NAME" "$CHECKUP_NOTIFICATIONS_ERROR_MESG"
       local exitCode=1
     fi
     [ -n "${STATUSBAR}" ] && pkill -RTMIN+8 "${STATUSBAR:?}"
   else
     local exitCode=1
   fi
+
+  # lets exit with code
   return "${exitCode:-$?}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-checkup "$@"
+checkup_main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
-# end
+# End application
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
diff --git a/bin/cmd_exists b/bin/cmd_exists
--- a/bin/cmd_exists
+++ b/bin/cmd_exists
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
-cmd_exists() {
+cmd_exists_main() {
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  PROG="cmd_exists"
+  PROG="$(basename $0)"
+  VERSION="202103230741-git"
   USER="${SUDO_USER:-${USER}}"
   HOME="${USER_HOME:-${HOME}}"
   SRC_DIR="${BASH_SOURCE%/*}"
@@ -9,68 +10,134 @@ cmd_exists() {
   #set opts
 
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  ##@Version       : 031120210447-git
+  ##@Version       : 202103230741-git
   # @Author        : Jason Hempstead
   # @Contact       : jason@casjaysdev.com
   # @License       : WTFPL
   # @ReadME        : cmd_exists --help
   # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-  # @Created       : Thursday, Mar 11, 2021 04:47 EST
+  # @Created       : Tuesday, Mar 23, 2021 07:41 EDT
   # @File          : cmd_exists
-  # @Description   : check if a script exists
+  # @Description   : check to see if the command exists
   # @TODO          :
   # @Other         :
   # @Resource      :
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  # Main function
-  if [ -f "/usr/local/bin/cmd_exists" ]; then
-    /usr/local/bin/cmd_exists "$@"
+  # Main function file
+  if [ -f "$SRC_DIR/functions.bash" ]; then
+    FUNCTIONS_DIR="$SRC_DIR"
+    . "$FUNCTIONS_DIR/functions.bash"
+  elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+    FUNCTIONS_DIR="$HOME/.local/bin"
+    . "$FUNCTIONS_DIR/functions.bash"
   else
-  __version() { app_version; }
-  __help() {
-    app_help "Usage: cmd_exists cmd  -  cmd_exists bash fish zsh" \
-      "-v, --version          -  display version" \
-      "-h, --help             -  display help"
-  }
-  if [ -f "$SRC_DIR/functions.bash" ]; then local DIR="$SRC_DIR"; else local DIR="$HOME/.local/bin"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    . "$DIR/functions.bash"
-  else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
     return 1
   fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  case "$1" in
-  -v | --version) __version ;;
-  -h | --help) __help ;;
-  *show) local show=true && shift 1 ;;
-  *err*) local error=show && shift 1 ;;
-  esac
+  # helper functions - See github.com/dfmgr/misc/bin/functions.bash
+  __version() { app_version; }
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  local exitCode=0
-  local missing=""
-  for f in "$@"; do
-    if [ -f "$(command -v "$f" 2>/dev/null)" ] || [ -f "$(type -P "$f" 2>/dev/null)" ]; then
-      found+="$f "
-      exitCode+=0
+  __help() {
+    app_help "4" "Usage: cmd_exists  -  cmd_exists --version" \
+      "-c, --config           -  create config file" \
+      "-a, --all              -  show all options" \
+      "-l, --list             -  used by completions" \
+      "-v, --version          -  display version" \
+      "-h, --help             -  display help"
+    exit $?
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __gen_config() {
+    printf_green "Generating the config file in"
+    printf_green "$CMD_EXISTS_CONFIG_DIR/$CMD_EXISTS_CONFIG_FILE"
+    [ -d "$CMD_EXISTS_CONFIG_DIR" ] || mkdir -p "$CMD_EXISTS_CONFIG_DIR"
+    [ -f "$CMD_EXISTS_CONFIG_DIR/$CMD_EXISTS_CONFIG_FILE" ] &&
+      cp -Rf "$CMD_EXISTS_CONFIG_DIR/$CMD_EXISTS_CONFIG_FILE" "$CMD_EXISTS_CONFIG_DIR/$CMD_EXISTS_CONFIG_FILE.$$"
+    cat <<EOF >"$CMD_EXISTS_CONFIG_DIR/$CMD_EXISTS_CONFIG_FILE"
+# Settings for cmd_exists
+CMD_EXISTS_NOTIFY="\${CMD_EXISTS_NOTIFY:-yes}"
+CMD_EXISTS_INSTALL="\${CMD_EXISTS_INSTALL:-yes}"
+
+EOF
+    if [ -f "$CMD_EXISTS_CONFIG_DIR/$CMD_EXISTS_CONFIG_FILE" ]; then
+      printf_green "Your config file for cmd_exists has been created"
+      true
     else
-      missing="$f "
-      exitCode+=1
+      printf_red "Failed to create the config file"
+      false
     fi
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Defaults
+  local exitCode= CMD_EXISTS_CONFIG_FILE= CMD_EXISTS_CONFIG_DIR= CMD_EXISTS_OPTIONS_DIR=
+  local CMD_EXISTS_CONFIG_FILE="settings.conf"
+  local CMD_EXISTS_CONFIG_DIR="$HOME/.config/misc/configs/cmd_exists"
+  local CMD_EXISTS_OPTIONS_DIR="$HOME/.local/share/misc/options/cmd_exists"
+  CMD_EXISTS_NOTIFY="${CMD_EXISTS_NOTIFY:-yes}"
+  CMD_EXISTS_INSTALL="${CMD_EXISTS_INSTALL:-yes}"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Argument/Option settings
+  local SETARGS="${*}"
+  local SHORTOPTS="a,l,c,v,h"
+  local LONGOPTS="all,list,config,version,help"
+  local ARRAY=""
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Generate Files
+  [ -f "$CMD_EXISTS_OPTIONS_DIR/options" ] || __list_options "$CMD_EXISTS_OPTIONS_DIR" "$ARRAY" &>/dev/null
+  [ -f "$CMD_EXISTS_OPTIONS_DIR/array" ] || __list_array "$CMD_EXISTS_OPTIONS_DIR" &>/dev/null
+  [ -f "$CMD_EXISTS_CONFIG_DIR/$CMD_EXISTS_CONFIG_FILE" ] || __gen_config &>/dev/null
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Import config
+  [ -f "$CMD_EXISTS_CONFIG_DIR/$CMD_EXISTS_CONFIG_FILE" ] && . "$CMD_EXISTS_CONFIG_DIR/$CMD_EXISTS_CONFIG_FILE"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  local setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -n "$PROG" -- "$@" 2>/dev/null)
+  eval set -- "$setopts" 2>/dev/null
+  while :; do
+    case $1 in
+    -a | --all)
+      __list_options "$CMD_EXISTS_OPTIONS_DIR" "$ARRAY"
+      exit $?
+      ;;
+    -l | --list)
+      __list_array "$CMD_EXISTS_OPTIONS_DIR"
+      exit $?
+      ;;
+    -v | --version)
+      __version
+      exit $?
+      ;;
+    -h | --help)
+      __help
+      exit $?
+      ;;
+    -c | --config)
+      __gen_config
+      exit $?
+      ;;
+    --)
+      shift 1
+      break
+      ;;
+      #*) break ;;
+    esac
+    shift
   done
-  [ "$show" = "true" ] && [ -n "$found" ] && printf_green "$found"
-  [ "$show" = "true" ] && [ -n "$found" ] && [ -n "$missing" ] && printf_red "$missing"
-  if [ "$error" = "show" ] && [ -n "$missing" ]; then
-    printf_red "Missing: $missing"
-    exitCode="1"
-  fi
-  fi
+  set -- "$SETARGS"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Check for required applications
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  __cmd_exists "$@"
+
+  # lets exit with code
   return "${exitCode:-$?}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-cmd_exists "$@"
+cmd_exists_main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
-# end
-
+# End application
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
diff --git a/bin/copy b/bin/copy
--- a/bin/copy
+++ b/bin/copy
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
-copy() {
+copy_main() {
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  PROG="copy"
+  PROG="$(basename $0)"
+  VERSION="202103231633-git"
   USER="${SUDO_USER:-${USER}}"
   HOME="${USER_HOME:-${HOME}}"
   SRC_DIR="${BASH_SOURCE%/*}"
@@ -9,56 +10,154 @@ copy() {
   #set opts
 
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  ##@Version       : 031120210522-git
+  ##@Version       : 202103231633-git
   # @Author        : Jason Hempstead
   # @Contact       : jason@casjaysdev.com
   # @License       : WTFPL
   # @ReadME        : copy --help
   # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-  # @Created       : Thursday, Mar 11, 2021 05:22 EST
+  # @Created       : Tuesday, Mar 23, 2021 16:33 EDT
   # @File          : copy
   # @Description   : copies a file and shows progress
   # @TODO          :
   # @Other         :
   # @Resource      :
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  # Main function
-  __version() { app_version; }
-  __help() {
-    app_help "Usage: copy source destination" \
-      "-v, --version          -  display version" \
-      "-h, --help             -  display help"
-  }
-  if [ -f "$SRC_DIR/functions.bash" ]; then local DIR="$SRC_DIR"; else local DIR="$HOME/.local/bin"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    . "$DIR/functions.bash"
+  # Main function file
+  if [ -f "$SRC_DIR/functions.bash" ]; then
+    FUNCTIONS_DIR="$SRC_DIR"
+    . "$FUNCTIONS_DIR/functions.bash"
+  elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+    FUNCTIONS_DIR="$HOME/.local/bin"
+    . "$FUNCTIONS_DIR/functions.bash"
   else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
     return 1
   fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  case $1 in
-  -v | --version) __version ;;
-  -h | --help) __help ;;
-  esac
-  [ -z "$1" ] || [ -z "$2" ] && __help
+  # helper functions - See github.com/dfmgr/misc/bin/functions.bash
+  __version() { app_version; }
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  cmd_exists --err dd || exit 1
-  typeset src="$1"
-  typeset dest="$2"
-  typeset size=$(stat -c%s "$src")
+  __help() {
+    app_help "4" "Usage: copy src dest" \
+      "-s, --source           -  Specify source" \
+      "-d, --dest             -  Specify destination" \
+      "-c, --config           -  create config file" \
+      "-a, --all              -  show all options" \
+      "-l, --list             -  used by completions" \
+      "-v, --version          -  display version" \
+      "-h, --help             -  display help"
+    exit $?
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __gen_config() {
+    printf_green "Generating the config file in"
+    printf_green "$COPY_CONFIG_DIR/$COPY_CONFIG_FILE"
+    [ -d "$COPY_CONFIG_DIR" ] || mkdir -p "$COPY_CONFIG_DIR"
+    [ -f "$COPY_CONFIG_DIR/$COPY_CONFIG_FILE" ] &&
+      cp -Rf "$COPY_CONFIG_DIR/$COPY_CONFIG_FILE" "$COPY_CONFIG_DIR/$COPY_CONFIG_FILE.$$"
+    cat <<EOF >"$COPY_CONFIG_DIR/$COPY_CONFIG_FILE"
+# Settings for copy
+COPY_CUSTOM_COMMAND=''
+
+EOF
+    if [ -f "$COPY_CONFIG_DIR/$COPY_CONFIG_FILE" ]; then
+      printf_green "Your config file for copy has been created"
+      true
+    else
+      printf_red "Failed to create the config file"
+      false
+    fi
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Defaults
+  local exitCode="" COPY_CONFIG_FILE="" COPY_CONFIG_DIR="" COPY_OPTIONS_DIR=""
+  local COPY_CONFIG_FILE="settings.conf"
+  local COPY_CONFIG_DIR="$HOME/.config/misc/configs/copy"
+  local COPY_OPTIONS_DIR="$HOME/.local/share/misc/options/copy"
+  local COPY_CUSTOM_COMMAND=''
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Argument/Option settings
+  local SETARGS="${*}"
+  local SHORTOPTS="a,l,c,v,h,s:,d:"
+  local LONGOPTS="all,list,config,version,help,source:,dest:"
+  local ARRAY=""
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Generate Files
+  [ -f "$COPY_OPTIONS_DIR/options" ] || __list_options "$COPY_OPTIONS_DIR" "$ARRAY" &>/dev/null
+  [ -f "$COPY_OPTIONS_DIR/array" ] || __list_array "$COPY_OPTIONS_DIR" &>/dev/null
+  [ -f "$COPY_CONFIG_DIR/$COPY_CONFIG_FILE" ] || __gen_config &>/dev/null
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Import config
+  [ -f "$COPY_CONFIG_DIR/$COPY_CONFIG_FILE" ] && . "$COPY_CONFIG_DIR/$COPY_CONFIG_FILE"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  local setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -n "$PROG" -- "$@" 2>/dev/null)
+  eval set -- "$setopts" 2>/dev/null
+  while :; do
+    case $1 in
+    -a | --all)
+      __list_options "$COPY_OPTIONS_DIR" "$ARRAY"
+      exit $?
+      ;;
+    -l | --list)
+      __list_array "$COPY_OPTIONS_DIR"
+      exit $?
+      ;;
+    -v | --version)
+      __version
+      exit $?
+      ;;
+    -h | --help)
+      __help
+      exit $?
+      ;;
+    -c | --config)
+      __gen_config
+      exit $?
+      ;;
+    -s | --source)
+      src="$2"
+      shift 1
+      ;;
+    -d | --dest)
+      dest="$2"
+      shift 1
+      ;;
+    --)
+      shift 1
+      break
+      ;;
+      #*) break ;;
+    esac
+    shift
+  done
+  set -- "$SETARGS"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Check for required applications
+  cmd_exists --error bash || exit 1
+  cmd_exists --error dd || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  typeset src="${1:-$src}"
+  typeset dest="${2:-$dest}"
+  typeset size="${size:-(stat -c%s "$src")}"
   [[ -d "$dest" ]] && dest="$dest/$(basename "$src")"
-  if [ -f "$(command -v pv)" ]; then
+  if [ -n "$COPY_CUSTOM_COMMAND" ]; then
+    $COPY_CUSTOM_COMMAND "$src" "$dest"
+  elif [ -f "$(command -v pv)" ]; then
     dd if="$src" 2>/dev/null | pv -petrb -s "$size" 2>/dev/null | dd of="$dest" 2>/dev/null
   else
     dd if="$src" of="$dest" status=progress 2>/dev/null
   fi
-  return $?
+
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # lets exit with code
+  return "${exitCode:-$?}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-copy "$@"
+copy_main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
+# End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# end
diff --git a/bin/countdown b/bin/countdown
--- a/bin/countdown
+++ b/bin/countdown
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
-countdown() {
+countdown_main() {
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  PROG="countdown"
+  PROG="$(basename $0)"
+  VERSION="202103231633-git"
   USER="${SUDO_USER:-${USER}}"
   HOME="${USER_HOME:-${HOME}}"
   SRC_DIR="${BASH_SOURCE%/*}"
@@ -9,41 +10,124 @@ countdown() {
   #set opts
 
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  ##@Version       : 031120210605-git
+  ##@Version       : 202103231633-git
   # @Author        : Jason Hempstead
   # @Contact       : jason@casjaysdev.com
   # @License       : WTFPL
   # @ReadME        : countdown --help
   # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-  # @Created       : Thursday, Mar 11, 2021 06:05 EST
+  # @Created       : Tuesday, Mar 23, 2021 16:33 EDT
   # @File          : countdown
   # @Description   : shows up/down seconds counter. Exits and produces a sound if reaches zero
   # @TODO          :
   # @Other         :
   # @Resource      :
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  # Main function
-  __version() { app_version; }
-  __help() {
-    app_help "Usage: countdown howLong  -  countdown 300" \
-      "-v, --version          -  display version" \
-      "-h, --help             -  display help"
-  }
-  if [ -f "$SRC_DIR/functions.bash" ]; then local DIR="$SRC_DIR"; else local DIR="$HOME/.local/bin"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    . "$DIR/functions.bash"
+  # Main function file
+  if [ -f "$SRC_DIR/functions.bash" ]; then
+    FUNCTIONS_DIR="$SRC_DIR"
+    . "$FUNCTIONS_DIR/functions.bash"
+  elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+    FUNCTIONS_DIR="$HOME/.local/bin"
+    . "$FUNCTIONS_DIR/functions.bash"
   else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
     return 1
   fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  case $1 in
-  -v | --version) __version ;;
-  -h | --help) __help ;;
-  esac
+  # helper functions - See github.com/dfmgr/misc/bin/functions.bash
+  __version() { app_version; }
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  cmd_exists --error showbanner || exit 1
+  __help() {
+    app_help "4" "Usage: countdown  -  countdown --version" \
+      "-c, --config           -  create config file" \
+      "-a, --all              -  show all options" \
+      "-l, --list             -  used by completions" \
+      "-v, --version          -  display version" \
+      "-h, --help             -  display help"
+    exit $?
+  }
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __gen_config() {
+    printf_green "Generating the config file in"
+    printf_green "$COUNTDOWN_CONFIG_DIR/$COUNTDOWN_CONFIG_FILE"
+    [ -d "$COUNTDOWN_CONFIG_DIR" ] || mkdir -p "$COUNTDOWN_CONFIG_DIR"
+    [ -f "$COUNTDOWN_CONFIG_DIR/$COUNTDOWN_CONFIG_FILE" ] &&
+      cp -Rf "$COUNTDOWN_CONFIG_DIR/$COUNTDOWN_CONFIG_FILE" "$COUNTDOWN_CONFIG_DIR/$COUNTDOWN_CONFIG_FILE.$$"
+    cat <<EOF >"$COUNTDOWN_CONFIG_DIR/$COUNTDOWN_CONFIG_FILE"
+# Settings for countdown
+COUNTDOWN_CUSTOM_COMMAND=''
+
+EOF
+    if [ -f "$COUNTDOWN_CONFIG_DIR/$COUNTDOWN_CONFIG_FILE" ]; then
+      printf_green "Your config file for countdown has been created"
+      true
+    else
+      printf_red "Failed to create the config file"
+      false
+    fi
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Defaults
+  local exitCode="" COUNTDOWN_CONFIG_FILE="" COUNTDOWN_CONFIG_DIR="" COUNTDOWN_OPTIONS_DIR=""
+  local COUNTDOWN_CONFIG_FILE="settings.conf"
+  local COUNTDOWN_CONFIG_DIR="$HOME/.config/misc/configs/countdown"
+  local COUNTDOWN_OPTIONS_DIR="$HOME/.local/share/misc/options/countdown"
+  local COUNTDOWN_CUSTOM_COMMAND=''
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Argument/Option settings
+  local SETARGS="${*}"
+  local SHORTOPTS="a,l,c,v,h"
+  local LONGOPTS="all,list,config,version,help"
+  local ARRAY=""
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Generate Files
+  [ -f "$COUNTDOWN_OPTIONS_DIR/options" ] || __list_options "$COUNTDOWN_OPTIONS_DIR" "$ARRAY" &>/dev/null
+  [ -f "$COUNTDOWN_OPTIONS_DIR/array" ] || __list_array "$COUNTDOWN_OPTIONS_DIR" &>/dev/null
+  [ -f "$COUNTDOWN_CONFIG_DIR/$COUNTDOWN_CONFIG_FILE" ] || __gen_config &>/dev/null
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Import config
+  [ -f "$COUNTDOWN_CONFIG_DIR/$COUNTDOWN_CONFIG_FILE" ] && . "$COUNTDOWN_CONFIG_DIR/$COUNTDOWN_CONFIG_FILE"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  local setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -n "$PROG" -- "$@" 2>/dev/null)
+  eval set -- "$setopts" 2>/dev/null
+  while :; do
+    case $1 in
+    -a | --all)
+      __list_options "$COUNTDOWN_OPTIONS_DIR" "$ARRAY"
+      exit $?
+      ;;
+    -l | --list)
+      __list_array "$COUNTDOWN_OPTIONS_DIR"
+      exit $?
+      ;;
+    -v | --version)
+      __version
+      exit $?
+      ;;
+    -h | --help)
+      __help
+      exit $?
+      ;;
+    -c | --config)
+      __gen_config
+      exit $?
+      ;;
+    --)
+      shift 1
+      break
+      ;;
+      #*) break ;;
+    esac
+    shift
+  done
+  set -- "$SETARGS"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Check for required applications
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
   local d="$1"
   typeset ts="$(($(date +%s) + ${1:-0} - 1))"
   export ts
@@ -55,17 +139,22 @@ countdown() {
   eval "$p1$p3"
   if [[ "$status" -eq 8 ]]; then
     notifications "Timer" "Your timer has gone off"
-    if [[ -f "$(command -v speaker-test)" ]]; then
+    if [ -n "$COUNTDOWN_CUSTOM_COMMAND" ]; then
+      $COUNTDOWN_CUSTOM_COMMAND
+    elif [[ -f "$(command -v speaker-test)" ]]; then
       speaker-test -t sine -f 1500 -S 70 -p 10000 -l 1 &>/dev/null
     elif [[ -f "$(command -v say)" ]]; then
       say "Your timer is going off"
     fi
   fi
+
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # lets exit with code
+  return "${exitCode:-$?}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-countdown "$@"
+countdown_main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
+# End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# end
diff --git a/bin/datauri b/bin/datauri
--- a/bin/datauri
+++ b/bin/datauri
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
-datauri() {
+datauri_main() {
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  PROG="datauri"
+  PROG="$(basename $0)"
+  VERSION="202103231633-git"
   USER="${SUDO_USER:-${USER}}"
   HOME="${USER_HOME:-${HOME}}"
   SRC_DIR="${BASH_SOURCE%/*}"
@@ -9,56 +10,148 @@ datauri() {
   #set opts
 
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  ##@Version       : 031120210622-git
+  ##@Version       : 202103231633-git
   # @Author        : Jason Hempstead
   # @Contact       : jason@casjaysdev.com
   # @License       : WTFPL
   # @ReadME        : datauri --help
   # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-  # @Created       : Thursday, Mar 11, 2021 06:22 EST
+  # @Created       : Tuesday, Mar 23, 2021 16:33 EDT
   # @File          : datauri
   # @Description   : Create data URI from a file
   # @TODO          :
   # @Other         :
   # @Resource      :
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  # Main function
-  __version() { app_version; }
-  __help() {
-    app_help "Usage: datauri fileName" \
-      "-v, --version          -  display version" \
-      "-h, --help             -  display help"
-  }
-  if [ -f "$SRC_DIR/functions.bash" ]; then local DIR="$SRC_DIR"; else local DIR="$HOME/.local/bin"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    . "$DIR/functions.bash"
+  # Main function file
+  if [ -f "$SRC_DIR/functions.bash" ]; then
+    FUNCTIONS_DIR="$SRC_DIR"
+    . "$FUNCTIONS_DIR/functions.bash"
+  elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+    FUNCTIONS_DIR="$HOME/.local/bin"
+    . "$FUNCTIONS_DIR/functions.bash"
   else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
     return 1
   fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  case $1 in
-  -v | --version) __version ;;
-  -h | --help) __help ;;
-  esac
+  # helper functions - See github.com/dfmgr/misc/bin/functions.bash
+  __version() { app_version; }
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __help() {
+    app_help "4" "Usage: datauri file" \
+      "-f, --file             -  specify the file" \
+      "-c, --config           -  create config file" \
+      "-a, --all              -  show all options" \
+      "-l, --list             -  used by completions" \
+      "-v, --version          -  display version" \
+      "-h, --help             -  display help"
+    exit $?
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __gen_config() {
+    printf_green "Generating the config file in"
+    printf_green "$DATAURI_CONFIG_DIR/$DATAURI_CONFIG_FILE"
+    [ -d "$DATAURI_CONFIG_DIR" ] || mkdir -p "$DATAURI_CONFIG_DIR"
+    [ -f "$DATAURI_CONFIG_DIR/$DATAURI_CONFIG_FILE" ] &&
+      cp -Rf "$DATAURI_CONFIG_DIR/$DATAURI_CONFIG_FILE" "$DATAURI_CONFIG_DIR/$DATAURI_CONFIG_FILE.$$"
+    cat <<EOF >"$DATAURI_CONFIG_DIR/$DATAURI_CONFIG_FILE"
+# Settings for datauri
+
+EOF
+    if [ -f "$DATAURI_CONFIG_DIR/$DATAURI_CONFIG_FILE" ]; then
+      printf_green "Your config file for datauri has been created"
+      true
+    else
+      printf_red "Failed to create the config file"
+      false
+    fi
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Defaults
+  local exitCode="" DATAURI_CONFIG_FILE="" DATAURI_CONFIG_DIR="" DATAURI_OPTIONS_DIR=""
+  local DATAURI_CONFIG_FILE="settings.conf"
+  local DATAURI_CONFIG_DIR="$HOME/.config/misc/configs/datauri"
+  local DATAURI_OPTIONS_DIR="$HOME/.local/share/misc/options/datauri"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Argument/Option settings
+  local SETARGS="${*}"
+  local SHORTOPTS="a,l,c,v,h,f:"
+  local LONGOPTS="all,list,config,version,help,file:"
+  local ARRAY=""
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Generate Files
+  [ -f "$DATAURI_OPTIONS_DIR/options" ] || __list_options "$DATAURI_OPTIONS_DIR" "$ARRAY" &>/dev/null
+  [ -f "$DATAURI_OPTIONS_DIR/array" ] || __list_array "$DATAURI_OPTIONS_DIR" &>/dev/null
+  [ -f "$DATAURI_CONFIG_DIR/$DATAURI_CONFIG_FILE" ] || __gen_config &>/dev/null
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Import config
+  [ -f "$DATAURI_CONFIG_DIR/$DATAURI_CONFIG_FILE" ] && . "$DATAURI_CONFIG_DIR/$DATAURI_CONFIG_FILE"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  local setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -n "$PROG" -- "$@" 2>/dev/null)
+  eval set -- "$setopts" 2>/dev/null
+  while :; do
+    case $1 in
+    -a | --all)
+      __list_options "$DATAURI_OPTIONS_DIR" "$ARRAY"
+      exit $?
+      ;;
+    -l | --list)
+      __list_array "$DATAURI_OPTIONS_DIR"
+      exit $?
+      ;;
+    -v | --version)
+      __version
+      exit $?
+      ;;
+    -h | --help)
+      __help
+      exit $?
+      ;;
+    -c | --config)
+      __gen_config
+      exit $?
+      ;;
+    -f | --file)
+      shift 1
+      file="$1"
+      ;;
+    --)
+      shift 1
+      break
+      ;;
+      #*) break ;;
+    esac
+    shift
+  done
+  set -- "$SETARGS"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Check for required applications
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
   typeset mimeType=""
-  if [ -f "$1" ]; then
+  local filename="${1:-file}"
+  if [ -f "$filename" ]; then
     mimeType=$(file -b --mime-type "$1")
     if [[ $mimeType == text/* ]]; then
       mimeType="$mimeType;charset=utf-8"
     fi
-    printf "data:%s;base64,%s" "$mimeType" "$(openssl base64 -in "$1" | tr -d "\n")"
-    echo ""
+    printf "data:%s;base64,%s" "$mimeType" "$(openssl base64 -in "$filename" | tr -d "\n")"
+    printf '\n'
   else
-    printf "%s is not a file.\n" "$1"
+    printf_red "%s is not a file.\n" "$filename"
     return 1
   fi
+
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # lets exit with code
+  return "${exitCode:-$?}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-datauri "$@"
+datauri_main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
+# End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# end
diff --git a/bin/delhistory b/bin/delhistory
--- a/bin/delhistory
+++ b/bin/delhistory
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
-delhistory() {
+delhistory_main() {
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  PROG="delhistory"
+  PROG="$(basename $0)"
+  VERSION="202103231633-git"
   USER="${SUDO_USER:-${USER}}"
   HOME="${USER_HOME:-${HOME}}"
   SRC_DIR="${BASH_SOURCE%/*}"
@@ -9,61 +10,151 @@ delhistory() {
   #set opts
 
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  ##@Version       : 031120210628-git
+  ##@Version       : 202103231633-git
   # @Author        : Jason Hempstead
   # @Contact       : jason@casjaysdev.com
   # @License       : WTFPL
   # @ReadME        : delhistory --help
   # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-  # @Created       : Thursday, Mar 11, 2021 06:28 EST
+  # @Created       : Tuesday, Mar 23, 2021 16:33 EDT
   # @File          : delhistory
   # @Description   : remove last n records from history
   # @TODO          :
   # @Other         :
   # @Resource      :
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  # Main function
-  __version() { app_version; }
-  __help() {
-    app_help "Usage delhistory Number  -  delhistory 10" \
-      "-v, --version          -  display version" \
-      "-h, --help             -  display help"
-  }
-  if [ -f "$SRC_DIR/functions.bash" ]; then local DIR="$SRC_DIR"; else local DIR="$HOME/.local/bin"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    source "$DIR/functions.bash"
+  # Main function file
+  if [ -f "$SRC_DIR/functions.bash" ]; then
+    FUNCTIONS_DIR="$SRC_DIR"
+    . "$FUNCTIONS_DIR/functions.bash"
+  elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+    FUNCTIONS_DIR="$HOME/.local/bin"
+    . "$FUNCTIONS_DIR/functions.bash"
   else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
     return 1
   fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  case $1 in
-  -v | --version) __version ;;
-  -h | --help) __help ;;
-  esac
+  # helper functions - See github.com/dfmgr/misc/bin/functions.bash
+  __version() { app_version; }
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  typeset opt id n=1
-  OPTIND=1 #reset index
-  while getopts "n:" opt; do
-    case $opt in
-    n) n=$OPTARG ;;
-    \?) exit 1 ;;
-    :)
-      printf_red "Option -$OPTARG requires number of history last entries to remove as an argument" >&2
-      return 1
-      ;;
-    esac
-  done
+  __help() {
+    app_help "4" "Usage: delhistory  -  delhistory --version" \
+      "-c, --config           -  create config file" \
+      "-a, --all              -  show all options" \
+      "-l, --list             -  used by completions" \
+      "-v, --version          -  display version" \
+      "-h, --help             -  display help"
+    exit $?
+  }
+  __delete_history() {
+    typeset opt id n=1
+    OPTIND=1 #reset index
+    while getopts "n:" opt; do
+      echo "$@"
+      exit
+      case $opt in
+      n) n=$OPTARG ;;
+      \?) exit 1 ;;
+      :)
+        printf_red "Option -$OPTARG requires number of history last entries to remove as an argument" >&2
+        return 1
+        ;;
+      esac
+    done
+    return $?
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __gen_config() {
+    printf_green "Generating the config file in"
+    printf_green "$DELHISTORY_CONFIG_DIR/$DELHISTORY_CONFIG_FILE"
+    [ -d "$DELHISTORY_CONFIG_DIR" ] || mkdir -p "$DELHISTORY_CONFIG_DIR"
+    [ -f "$DELHISTORY_CONFIG_DIR/$DELHISTORY_CONFIG_FILE" ] &&
+      cp -Rf "$DELHISTORY_CONFIG_DIR/$DELHISTORY_CONFIG_FILE" "$DELHISTORY_CONFIG_DIR/$DELHISTORY_CONFIG_FILE.$$"
+    cat <<EOF >"$DELHISTORY_CONFIG_DIR/$DELHISTORY_CONFIG_FILE"
+# Settings for delhistory
 
+EOF
+    if [ -f "$DELHISTORY_CONFIG_DIR/$DELHISTORY_CONFIG_FILE" ]; then
+      printf_green "Your config file for delhistory has been created"
+      true
+    else
+      printf_red "Failed to create the config file"
+      false
+    fi
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Defaults
+  local exitCode="" DELHISTORY_CONFIG_FILE="" DELHISTORY_CONFIG_DIR="" DELHISTORY_OPTIONS_DIR=""
+  local DELHISTORY_CONFIG_FILE="settings.conf"
+  local DELHISTORY_CONFIG_DIR="$HOME/.config/misc/configs/delhistory"
+  local DELHISTORY_OPTIONS_DIR="$HOME/.local/share/misc/options/delhistory"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Argument/Option settings
+  local SETARGS="${*}"
+  local SHORTOPTS="a,l,c,v,h"
+  local LONGOPTS="all,list,config,version,help"
+  local ARRAY=""
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Generate Files
+  [ -f "$DELHISTORY_OPTIONS_DIR/options" ] || __list_options "$DELHISTORY_OPTIONS_DIR" "$ARRAY" &>/dev/null
+  [ -f "$DELHISTORY_OPTIONS_DIR/array" ] || __list_array "$DELHISTORY_OPTIONS_DIR" &>/dev/null
+  [ -f "$DELHISTORY_CONFIG_DIR/$DELHISTORY_CONFIG_FILE" ] || __gen_config &>/dev/null
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Import config
+  [ -f "$DELHISTORY_CONFIG_DIR/$DELHISTORY_CONFIG_FILE" ] && . "$DELHISTORY_CONFIG_DIR/$DELHISTORY_CONFIG_FILE"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  local setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -n "$PROG" -- "$@" 2>/dev/null)
+  eval set -- "$setopts" 2>/dev/null
+  while :; do
+    case $1 in
+    -a | --all)
+      __list_options "$DELHISTORY_OPTIONS_DIR" "$ARRAY"
+      exit $?
+      ;;
+    -l | --list)
+      __list_array "$DELHISTORY_OPTIONS_DIR"
+      exit $?
+      ;;
+    -v | --version)
+      __version
+      exit $?
+      ;;
+    -h | --help)
+      __help
+      exit $?
+      ;;
+    -c | --config)
+      __gen_config
+      exit $?
+      ;;
+    --)
+      shift 1
+      break
+      ;;
+      #*) break ;;
+    esac
+    shift
+  done
+  set -- "$SETARGS"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Check for required applications
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  __delete_history "$@"
   ((++n))
   id=$(history | tail -n $n | head -n1 | awk '{print $1}')
   while ((n-- > 0)); do history -d "$id"; done
-  return $?
+
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # lets exit with code
+  return "${exitCode:-$?}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-delhistory "$@"
+delhistory_main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
+# End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# end
diff --git a/bin/dmenu_edit_conf b/bin/dmenu_edit_conf
--- a/bin/dmenu_edit_conf
+++ b/bin/dmenu_edit_conf
@@ -1,63 +1,161 @@
 #!/usr/bin/env bash
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-PROG="$(basename $0)"
-USER="${SUDO_USER:-${USER}}"
-HOME="${USER_HOME:-${HOME}}"
-SRC_DIR="${BASH_SOURCE%/*}"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-#set opts
+dmenu_edit_conf_main() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  PROG="$(basename $0)"
+  VERSION="202103231633-git"
+  USER="${SUDO_USER:-${USER}}"
+  HOME="${USER_HOME:-${HOME}}"
+  SRC_DIR="${BASH_SOURCE%/*}"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  #set opts
 
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 202103222059-git
-# @Author        : Jason Hempstead
-# @Contact       : jason@casjaysdev.com
-# @License       : WTFPL
-# @ReadME        : dmenu_edit_conf --help
-# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Monday, Mar 22, 2021 20:59 EDT
-# @File          : dmenu_edit_conf
-# @Description   : dmenu for editing configuration files
-# @TODO          : Move to misc user scripts
-# @Other         :
-# @Resource      :
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Main function file
-if [ -f "$SRC_DIR/functions.bash" ]; then
-  FUNCTIONS_DIR="$SRC_DIR"
-  . "$FUNCTIONS_DIR/functions.bash"
-elif [ -f "$HOME/.local/bin/functions.bash" ]; then
-  FUNCTIONS_DIR="$HOME/.local/bin"
-  . "$FUNCTIONS_DIR/functions.bash"
-else
-  printf "\t\t\033[0;31m%s \033[0m\n" "Could not source the functions file from $\FUNCTIONS_DIR"
-  return 1
-fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-[ "$(uname)" = Linux ] || exit 1
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-DMENU_EDIT_CONFIG_DIR="${DMENU_EDIT_CONFIG_DIR:-$HOME/.config/dmenu_edit_conf}"
-DMENU_USER_CONF="${DMENU_USER_CONF:-$DMENU_EDIT_CONFIG_DIR/menus}"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if cmd_exists rofi; then
-  __dmenu() { rofi -show -dmenu -i -p 'Edit config file: '; }
-elif cmd_exists dmenu; then
-  __dmenu() { dmenu -i -p 'Edit config file: '; }
-else
-  notifications "$PROG" "This requires either dmenu or rofi"
-fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [ -d "$DMENU_USER_CONF" ]; then
-  EDIT_NAME="$(cd "$DMENU_USER_CONF" && find * -maxdepth 3 -type f | __dmenu)"
-  . "$DMENU_USER_CONF/$EDIT_NAME"
-fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [ -f "$editConfig" ]; then
-  myeditor "$editConfig"
-else
-  notifications "$PROG" "Can not find the file: $editConfig" || printf_exit "Can not find the file: $editConfig"
-fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# end
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  ##@Version       : 202103231633-git
+  # @Author        : Jason Hempstead
+  # @Contact       : jason@casjaysdev.com
+  # @License       : WTFPL
+  # @ReadME        : dmenu_edit_conf --help
+  # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+  # @Created       : Tuesday, Mar 23, 2021 16:33 EDT
+  # @File          : dmenu_edit_conf
+  # @Description   : dmenu for editing configuration files
+  # @TODO          : Move to misc user scripts
+  # @Other         :
+  # @Resource      :
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Main function file
+  if [ -f "$SRC_DIR/functions.bash" ]; then
+    FUNCTIONS_DIR="$SRC_DIR"
+    . "$FUNCTIONS_DIR/functions.bash"
+  elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+    FUNCTIONS_DIR="$HOME/.local/bin"
+    . "$FUNCTIONS_DIR/functions.bash"
+  else
+    printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # helper functions - See github.com/dfmgr/misc/bin/functions.bash
+  __version() { app_version; }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __help() {
+    app_help "4" "Usage: dmenu_edit_conf  -  dmenu_edit_conf --version" \
+      "-c, --config           -  create config file" \
+      "-a, --all              -  show all options" \
+      "-l, --list             -  used by completions" \
+      "-v, --version          -  display version" \
+      "-h, --help             -  display help"
+    exit $?
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __gen_config() {
+    printf_green "Generating the config file in"
+    printf_green "$DMENU_EDIT_CONF_CONFIG_DIR/$DMENU_EDIT_CONF_CONFIG_FILE"
+    [ -d "$DMENU_EDIT_CONF_CONFIG_DIR" ] || mkdir -p "$DMENU_EDIT_CONF_CONFIG_DIR"
+    [ -f "$DMENU_EDIT_CONF_CONFIG_DIR/$DMENU_EDIT_CONF_CONFIG_FILE" ] &&
+      cp -Rf "$DMENU_EDIT_CONF_CONFIG_DIR/$DMENU_EDIT_CONF_CONFIG_FILE" "$DMENU_EDIT_CONF_CONFIG_DIR/$DMENU_EDIT_CONF_CONFIG_FILE.$$"
+    cat <<EOF >"$DMENU_EDIT_CONF_CONFIG_DIR/$DMENU_EDIT_CONF_CONFIG_FILE"
+# Settings for dmenu_edit_conf
+DMENU_EDIT_USER_CONF_DIR="${DMENU_EDIT_USER_CONF_DIR:-$DMENU_EDIT_CONF_CONFIG_DIR/menus}"
 
+EOF
+    if [ -f "$DMENU_EDIT_CONF_CONFIG_DIR/$DMENU_EDIT_CONF_CONFIG_FILE" ]; then
+      printf_green "Your config file for dmenu_edit_conf has been created"
+      true
+    else
+      printf_red "Failed to create the config file"
+      false
+    fi
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Defaults
+  local exitCode="" DMENU_EDIT_CONF_CONFIG_FILE="" DMENU_EDIT_CONF_CONFIG_DIR="" DMENU_EDIT_CONF_OPTIONS_DIR=""
+  local DMENU_EDIT_CONF_CONFIG_FILE="settings.conf"
+  local DMENU_EDIT_CONF_CONFIG_DIR="$HOME/.config/misc/configs/dmenu_edit_conf"
+  local DMENU_EDIT_CONF_OPTIONS_DIR="$HOME/.local/share/misc/options/dmenu_edit_conf"
+  local DMENU_EDIT_USER_CONF_DIR="${DMENU_EDIT_USER_CONF_DIR:-$DMENU_EDIT_CONF_CONFIG_DIR/menus}"
+
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Argument/Option settings
+  local SETARGS="${*}"
+  local SHORTOPTS="a,l,c,v,h"
+  local LONGOPTS="all,list,config,version,help"
+  local ARRAY=""
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Generate Files
+  [ -f "$DMENU_EDIT_CONF_OPTIONS_DIR/options" ] || __list_options "$DMENU_EDIT_CONF_OPTIONS_DIR" "$ARRAY" &>/dev/null
+  [ -f "$DMENU_EDIT_CONF_OPTIONS_DIR/array" ] || __list_array "$DMENU_EDIT_CONF_OPTIONS_DIR" &>/dev/null
+  [ -f "$DMENU_EDIT_CONF_CONFIG_DIR/$DMENU_EDIT_CONF_CONFIG_FILE" ] || __gen_config &>/dev/null
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Import config
+  [ -f "$DMENU_EDIT_CONF_CONFIG_DIR/$DMENU_EDIT_CONF_CONFIG_FILE" ] && . "$DMENU_EDIT_CONF_CONFIG_DIR/$DMENU_EDIT_CONF_CONFIG_FILE"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  local setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -n "$PROG" -- "$@" 2>/dev/null)
+  eval set -- "$setopts" 2>/dev/null
+  while :; do
+    case $1 in
+    -a | --all)
+      __list_options "$DMENU_EDIT_CONF_OPTIONS_DIR" "$ARRAY"
+      exit $?
+      ;;
+    -l | --list)
+      __list_array "$DMENU_EDIT_CONF_OPTIONS_DIR"
+      exit $?
+      ;;
+    -v | --version)
+      __version
+      exit $?
+      ;;
+    -h | --help)
+      __help
+      exit $?
+      ;;
+    -c | --config)
+      __gen_config
+      exit $?
+      ;;
+    --)
+      shift 1
+      break
+      ;;
+      #*) break ;;
+    esac
+    shift
+  done
+  set -- "$SETARGS"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Check for required applications
+  cmd_exists --error bash || exit 1
+  [ "$(uname)" = Linux ] || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  if cmd_exists rofi; then
+    __dmenu() { rofi -show -dmenu -i -p 'Edit config file: '; }
+  elif cmd_exists dmenu; then
+    __dmenu() { dmenu -i -p 'Edit config file: '; }
+  else
+    notifications "$PROG" "This requires either dmenu or rofi"
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if [ -d "$DMENU_EDIT_USER_CONF_DIR" ]; then
+    EDIT_NAME="$(cd "$DMENU_EDIT_USER_CONF_DIR" && find * -maxdepth 3 -type f | __dmenu)"
+    . "$DMENU_EDIT_USER_CONF_DIR/$EDIT_NAME"
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if [ -f "$editConfig" ]; then
+    myeditor "$editConfig"
+  else
+    notifications "$PROG" "Can not find the file: $editConfig" || printf_exit "Can not find the file: $editConfig"
+  fi
+
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # lets exit with code
+  return "${exitCode:-$?}"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# execute function
+dmenu_edit_conf_main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# End application
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
