🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/ex b/bin/ex
--- a/bin/ex
+++ b/bin/ex
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
-ex() {
+ex_main() {
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  PROG="ex"
+  PROG="$(basename $0)"
+  VERSION="202103231633-git"
   USER="${SUDO_USER:-${USER}}"
   HOME="${USER_HOME:-${HOME}}"
   SRC_DIR="${BASH_SOURCE%/*}"
@@ -9,64 +10,156 @@ ex() {
   #set opts
 
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  ##@Version       : 031120210633-git
+  ##@Version       : 202103231633-git
   # @Author        : Jason Hempstead
   # @Contact       : jason@casjaysdev.com
   # @License       : WTFPL
   # @ReadME        : ex --help
   # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-  # @Created       : Thursday, Mar 11, 2021 06:33 EST
+  # @Created       : Tuesday, Mar 23, 2021 16:33 EDT
   # @File          : ex
-  # @Description   : archive extractor
+  # @Description   :
   # @TODO          :
   # @Other         :
   # @Resource      :
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  # Main function
-  __version() { app_version; }
-  __help() {
-    app_help "Usage: ex fileName" \
-      "-v, --version          -  display version" \
-      "-h, --help             -  display help"
-  }
-  if [ -f "$SRC_DIR/functions.bash" ]; then local DIR="$SRC_DIR"; else local DIR="$HOME/.local/bin"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    . "$DIR/functions.bash"
+  # Main function file
+  if [ -f "$SRC_DIR/functions.bash" ]; then
+    FUNCTIONS_DIR="$SRC_DIR"
+    . "$FUNCTIONS_DIR/functions.bash"
+  elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+    FUNCTIONS_DIR="$HOME/.local/bin"
+    . "$FUNCTIONS_DIR/functions.bash"
   else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
     return 1
   fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  case $1 in
-  -v | --version) __version ;;
-  -h | --help) __help ;;
-  esac
+  # helper functions - See github.com/dfmgr/misc/bin/functions.bash
+  __version() { app_version; }
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  if [ -f $1 ]; then
+  __help() {
+    app_help "4" "Usage: ex file" \
+      "-f, --file             -  specify file" \
+      "-c, --config           -  create config file" \
+      "-a, --all              -  show all options" \
+      "-l, --list             -  used by completions" \
+      "-v, --version          -  display version" \
+      "-h, --help             -  display help"
+    exit $?
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __gen_config() {
+    printf_green "Generating the config file in"
+    printf_green "$EX_CONFIG_DIR/$EX_CONFIG_FILE"
+    [ -d "$EX_CONFIG_DIR" ] || mkdir -p "$EX_CONFIG_DIR"
+    [ -f "$EX_CONFIG_DIR/$EX_CONFIG_FILE" ] &&
+      cp -Rf "$EX_CONFIG_DIR/$EX_CONFIG_FILE" "$EX_CONFIG_DIR/$EX_CONFIG_FILE.$$"
+    cat <<EOF >"$EX_CONFIG_DIR/$EX_CONFIG_FILE"
+# Settings for ex
+
+EOF
+    if [ -f "$EX_CONFIG_DIR/$EX_CONFIG_FILE" ]; then
+      printf_green "Your config file for ex has been created"
+      true
+    else
+      printf_red "Failed to create the config file"
+      false
+    fi
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Defaults
+  local exitCode="" EX_CONFIG_FILE="" EX_CONFIG_DIR="" EX_OPTIONS_DIR=""
+  local EX_CONFIG_FILE="settings.conf"
+  local EX_CONFIG_DIR="$HOME/.config/misc/configs/ex"
+  local EX_OPTIONS_DIR="$HOME/.local/share/misc/options/ex"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Argument/Option settings
+  local SETARGS="${*}"
+  local SHORTOPTS="a,l,c,v,h,f:"
+  local LONGOPTS="all,list,config,version,help,file:"
+  local ARRAY=""
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Generate Files
+  [ -f "$EX_OPTIONS_DIR/options" ] || __list_options "$EX_OPTIONS_DIR" "$ARRAY" &>/dev/null
+  [ -f "$EX_OPTIONS_DIR/array" ] || __list_array "$EX_OPTIONS_DIR" &>/dev/null
+  [ -f "$EX_CONFIG_DIR/$EX_CONFIG_FILE" ] || __gen_config &>/dev/null
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Import config
+  [ -f "$EX_CONFIG_DIR/$EX_CONFIG_FILE" ] && . "$EX_CONFIG_DIR/$EX_CONFIG_FILE"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  local setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -n "$PROG" -- "$@" 2>/dev/null)
+  eval set -- "$setopts" 2>/dev/null
+  while :; do
     case $1 in
-    *.tar.bz2) tar xjf $1 ;;
-    *.tar.gz) tar xzf $1 ;;
-    *.bz2) bunzip2 $1 ;;
-    *.rar) unrar x $1 ;;
-    *.gz) gunzip $1 ;;
-    *.tar) tar xf $1 ;;
-    *.tbz2) tar xjf $1 ;;
-    *.tgz) tar xzf $1 ;;
-    *.zip) unzip $1 ;;
-    *.Z) uncompress $1 ;;
-    *.7z) 7z x $1 ;;
-    *) printf_red "$1 cannot be extracted via ex" && return 1 ;;
+    -a | --all)
+      __list_options "$EX_OPTIONS_DIR" "$ARRAY"
+      exit $?
+      ;;
+    -l | --list)
+      __list_array "$EX_OPTIONS_DIR"
+      exit $?
+      ;;
+    -v | --version)
+      __version
+      exit $?
+      ;;
+    -h | --help)
+      __help
+      exit $?
+      ;;
+    -c | --config)
+      __gen_config
+      exit $?
+      ;;
+    -f | --file)
+      shift 1
+      file="$1"
+      ;;
+    --)
+      shift 1
+      break
+      ;;
+      #*) break ;;
+    esac
+    shift
+  done
+  set -- "$SETARGS"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Check for required applications
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  filename="${file:-$1}"
+  if [ -f "$filename" ]; then
+    case "$filename" in
+    *.tar.bz2) tar xjf "$filename" ;;
+    *.tar.gz) tar xzf "$filename" ;;
+    *.bz2) bunzip2 "$filename" ;;
+    *.rar) unrar x "$filename" ;;
+    *.gz) gunzip "$filename" ;;
+    *.tar) tar xf "$filename" ;;
+    *.tbz2) tar xjf "$filename" ;;
+    *.tgz) tar xzf "$filename" ;;
+    *.zip) unzip "$filename" ;;
+    *.Z) uncompress "$filename" ;;
+    *.7z) 7z x "$filename" ;;
+    *) printf_red ""$filename" cannot be extracted via ex" && return 1 ;;
     esac
     return $?
   else
-    printf_red "$1 is not a valid file"
+    printf_red ""$filename" is not a valid file"
     return 1
   fi
+
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # lets exit with code
+  return "${exitCode:-$?}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-ex "$@"
+ex_main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
+# End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# end
