🗃 Modified: bin/setup_gvm  🗃

diff --git a/bin/setup_gvm b/bin/setup_gvm
--- a/bin/setup_gvm
+++ b/bin/setup_gvm
@@ -1,107 +1,192 @@
 #!/usr/bin/env bash
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-PROG="setup_gvm"
-USER="${SUDO_USER:-${USER}}"
-HOME="${USER_HOME:-${HOME}}"
-SRC_DIR="${BASH_SOURCE%/*}"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-#set opts
+setup_gvm_main() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  PROG="$(basename "$0")"
+  VERSION="202107281513-git"
+  USER="${SUDO_USER:-${USER}}"
+  HOME="${USER_HOME:-${HOME}}"
+  SRC_DIR="${BASH_SOURCE%/*}"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  #set opts
+  trap 'exitCode=${exitCode:-$?};[ -f "$SETUP_GVM_TEMP_FILE" ] && rm -Rf "$SETUP_GVM_TEMP_FILE" &>/dev/null' EXIT
 
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 031520211424-git
-# @Author        : Jason Hempstead
-# @Contact       : jason@casjaysdev.com
-# @License       : WTFPL
-# @ReadME        : setup_gvm --help
-# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Monday, Mar 15, 2021 14:24 EDT
-# @File          : setup_gvm
-# @Description   : GO Version Manager installer
-# @TODO          :
-# @Other         :
-# @Resource      :
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Main function file
-if [ -f "$SRC_DIR/functions.bash" ]; then
-  FUNCTIONS_DIR="$SRC_DIR"
-  . "$FUNCTIONS_DIR/functions.bash"
-elif [ -f "$HOME/.local/bin/functions.bash" ]; then
-  FUNCTIONS_DIR="$HOME/.local/bin"
-  . "$FUNCTIONS_DIR/functions.bash"
-else
-  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
-  return 1
-fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# helper function
-__version() { app_version; }
-__help() {
-  app_help "Usage: setup_gvm  -  setup_gvm --version" \
-    "-v, --version          -  display version" \
-    "-h, --help             -  display help"
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-installcmd() {
-  curl -q -fsSL "https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer" |
-    bash -s -- master "$GVM_ROOT" &>/dev/null && return 0 || return 1
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Main function
-main() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  ##@Version       : 202107281513-git
+  # @Author        : jason
+  # @Contact       : jason
+  # @License       : LICENSE.md
+  # @ReadME        : setup_gvm --help
+  # @Copyright     : Copyright: (c) 2021 Jason Hempstead, Casjays Developments
+  # @Created       : Wednesday, Jul 28, 2021 20:29 EDT
+  # @File          : setup_gvm
+  # @Description   :
+  # @TODO          :
+  # @Other         :
+  # @Resource      :
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Main function file
+  if [ -f "$SRC_DIR/functions.bash" ]; then
+    FUNCTIONS_DIR="$SRC_DIR"
+    . "$FUNCTIONS_DIR/functions.bash"
+  elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+    FUNCTIONS_DIR="$HOME/.local/bin"
+    . "$FUNCTIONS_DIR/functions.bash"
+  else
+    printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # helper functions - See https://github.com/dfmgr/misc/blob/main/bin/functions.bash
+  __version() { app_version; }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __help() {
+    app_help "4" "Usage: setup_gvm [options]  " \
+      "-c, --config           -  create config file" \
+      "-v, --version          -  display version" \
+      "-h, --help             -  display help" \
+      "--options              -  used by completions"
+    exit $?
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __gen_config() {
+    printf_green "Generating the config file in"
+    printf_green "$SETUP_GVM_CONFIG_DIR/$SETUP_GVM_CONFIG_FILE"
+    [ -d "$SETUP_GVM_CONFIG_DIR" ] || mkdir -p "$SETUP_GVM_CONFIG_DIR"
+    [ -d "$SETUP_GVM_CONFIG_BACKUP_DIR" ] || mkdir -p "$SETUP_GVM_CONFIG_BACKUP_DIR"
+    [ -f "$SETUP_GVM_CONFIG_DIR/$SETUP_GVM_CONFIG_FILE" ] &&
+      cp -Rf "$SETUP_GVM_CONFIG_DIR/$SETUP_GVM_CONFIG_FILE" "$SETUP_GVM_CONFIG_BACKUP_DIR/$SETUP_GVM_CONFIG_FILE.$$"
+    cat <<EOF >"$SETUP_GVM_CONFIG_DIR/$SETUP_GVM_CONFIG_FILE"
+# Settings for SETUP_GVM
+SETUP_GVM_NOTIFY_ENABLED="yes"
+SETUP_GVM_NOTIFY_CLIENT_NAME="${NOTIFY_CLIENT_NAME:-$PROG}"
+SETUP_GVM_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$SETUP_GVM_NOTIFY_CLIENT_ICON}"
+SETUP_GVM_INSTALL_SCRIPT="${SETUP_GVM_INSTALL_SCRIPT:-https://deno.land/x/install/install.sh}"
+
+EOF
+    if [ -f "$SETUP_GVM_CONFIG_DIR/$SETUP_GVM_CONFIG_FILE" ]; then
+      printf_green "Your config file for SETUP_GVM has been created"
+      true
+    else
+      printf_red "Failed to create the config file"
+      false
+    fi
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  __deno_install() {
+    if [[ "$1" != "-f" ]] && cmd_exists deno; then
+      printf_green "deno is already installed "
+      printf_blue "run $PROG --install to updated"
+      return 0
+    else
+      curl -q -LSs "$SETUP_GVM_INSTALL_SCRIPT" | bash &>/dev/null
+      if type -P deno &>/dev/null; then
+        printf_green "deno has been installed"
+        return 0
+      else
+        printf_red "Failed to install deno"
+        return 1
+      fi
+    fi
+  }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Defaults
+  local exitCode=""
+  local SETUP_GVM_CONFIG_FILE="settings.conf"
+  local SETUP_GVM_CONFIG_DIR="$HOME/.config/misc/setup_gvm"
+  local SETUP_GVM_CONFIG_BACKUP_DIR="$HOME/.local/share/misc/setup_gvm/backups"
+  local SETUP_GVM_OPTIONS_DIR="$HOME/.local/share/misc/setup_gvm/options"
+  local SETUP_GVM_TEMP_FILE="${TMPDIR:-/tmp}/setup_gvm"
+  local SETUP_GVM_NOTIFY_ENABLED="yes"
+  local SETUP_GVM_NOTIFY_CLIENT_NAME="${NOTIFY_CLIENT_NAME:-$PROG}"
+  local SETUP_GVM_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$SETUP_GVM_NOTIFY_CLIENT_ICON}"
+  local SETUP_GVM_INSTALL_SCRIPT="${SETUP_GVM_INSTALL_SCRIPT:-https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer}"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Argument/Option settings
+  local SETARGS="$*"
+  local SHORTOPTS="c,v,h,i,f"
+  local LONGOPTS="options,config,version,help,force"
+  local ARRAY=""
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Generate Files
+  [ -f "$SETUP_GVM_CONFIG_DIR/$SETUP_GVM_CONFIG_FILE" ] || __gen_config &>/dev/null
+  [ -f "$SETUP_GVM_OPTIONS_DIR/options" ] || __list_options "$SETUP_GVM_OPTIONS_DIR" &>/dev/null
+  [ -f "$SETUP_GVM_OPTIONS_DIR/array" ] || __list_array "$SETUP_GVM_OPTIONS_DIR" "$ARRAY" &>/dev/null
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Import config
+  if [ -f "$SETUP_GVM_CONFIG_DIR/$SETUP_GVM_CONFIG_FILE" ]; then
+    . "$SETUP_GVM_CONFIG_DIR/$SETUP_GVM_CONFIG_FILE"
+  fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # options
-  case $1 in
-  -v | --version) __version ;;
-  -h | --help) __help ;;
-  esac
+  local setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -a -n "$PROG" -- "$@" 2>/dev/null)
+  eval set -- "${setopts}" 2>/dev/null
+  while :; do
+    case $1 in
+    --options)
+      shift 1
+      __list_array "$SETUP_GVM_OPTIONS_DIR" "$ARRAY"
+      __list_options "$SETUP_GVM_OPTIONS_DIR"
+      exit $?
+      ;;
+    -v | --version)
+      shift 1
+      __version
+      exit $?
+      ;;
+    -h | --help)
+      shift 1
+      __help
+      exit $?
+      ;;
+    -c | --config)
+      shift 1
+      __gen_config
+      exit $?
+      ;;
+    -f | --force)
+      shift 1
+      __deno_install -f
+      exit $?
+      ;;
+    --)
+      shift 1
+      break
+      ;;
+      #*) break ;;
+    esac
+  done
+  #set -- "$SETARGS"
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  # Required app check
-  cmd_exists --error bash curl git || exit 1
-  am_i_online --error || return 1
-  if [ -n "$NODE_MANAGER" ]; then
-    [ "$NODE_MANAGER" != "gvm" ] && exit 0
+  # Actions based on env
+  export NOTIFY_CLIENT_NAME="${SETUP_GVM_NOTIFY_CLIENT_NAME}"
+  export NOTIFY_CLIENT_ICON="${SETUP_GVM_NOTIFY_CLIENT_ICON}"
+  if [ "$SETUP_GVM_NOTIFY_ENABLED" = "yes" ]; then
+    __notifications() {
+      notifications "$*" || return 1
+    }
+  else
+    __notifications() { false; }
   fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Check for required applications/Network check
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # APP Variables
+  GVM_ROOT="${GVM_ROOT:-$HOME/.local/share/gvm}"
+  PATH="$GVM_ROOT/bin:$PATH"
+  export GVM_ROOT PATH
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # begin main app
-  exitCode=0
-  GVM_ROOT="${GVM_ROOT:-$HOME/.local/share/gvm}"
-  export GVM_ROOT
+  __deno_install || exit 1
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  if [[ "$*" == "--remove" ]]; then
-    printf_red "Removing GVM from your system"
-    [[ -d "$GVM_ROOT" ]] && rm -Rf "$GVM_ROOT"
-    if [ ! -d "$GVM_ROOT/.git" ] && [ -z "$(command -v gvm 2>/dev/null)" ]; then
-      printf_green "GVM Has been removed"
-    fi
-    exit $?
-  fi
-
-  printf_red "installing GVM to $GVM_ROOT"
-  mkdir -p "$GVM_ROOT"
-  if [ -d "$GVM_ROOT/.git" ]; then
-    printf_blue "Updating GVM"
-    git -C $GVM_ROOT pull -q &>/dev/null
-  else
-    printf_blue "Running the GVM script"
-    installcmd || printf_exit "Failed to install GVM"
-  fi
-  if [ -n "$(command -v gvm 2>/dev/null)" ]; then
-    printf_blue "Setting up GVM"
-    gvm install "$GVM_NODE_VERSION" &>/dev/null
-    gvm ls | grep -q "$GVM_NODE_VERSION" && gvm use "$GVM_NODE_VERSION" &>/dev/null
-  fi
-  if [ -n "$(command -v gvm 2>/dev/null)" ]; then
-    printf_green "GVM has been installed"
-  else
-    printf_red "GVM Failed to install"
-    exitcode=1
-  fi
-  return "${exitCode:-$?}"
+  # lets exit with code
+  return ${exitCode:-$?}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
-main "$@"
+setup_gvm_main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
+# End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# end
+# lets exit with code
+exit ${exitCode:-$?}
