🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/setverfile b/bin/setverfile
--- a/bin/setverfile
+++ b/bin/setverfile
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-PROG="git_clone"
+APPNAME="setverfile"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
@@ -8,42 +8,56 @@ SRC_DIR="${BASH_SOURCE%/*}"
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 031120210655-git
+##@Version       : 031620210827-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
-# @License       : WTFPL
-# @ReadME        : git_clone --help
+# @License       : LICENSE.md
+# @ReadME        : setverfile --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Thursday, Mar 11, 2021 06:55 EST
-# @File          : git_clone
-# @Description   : clone a git repo and delete the directory if it exits
-# @TODO          :
+# @Created       : Tuesday, Mar 16, 2021 15:47 EDT
+# @File          : setverfile
+# @Description   : Set the version for git repo
+# @TODO          : Refactor code
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Main function
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# helper function
 __version() { app_version; }
 __help() {
-  app_help "Usage: git_clone remote local" \
+  app_help "Usage: setverfile  -  setverfile --version" \
     "-v, --version          -  display version" \
     "-h, --help             -  display help"
 }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
 main() {
-  if [ -f "$SRC_DIR/functions.bash" ]; then local DIR="$SRC_DIR"; else local DIR="$HOME/.local/bin"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    . "$DIR/functions.bash"
-  else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
-    return 1
-  fi
+  local datetimeformat="${SETVER_FORMAT:-%m%d%Y%H%M}"
+  local setvertype="${SETVER_TYPE:--git}"
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  __git() { am_i_online && git clone -q "$1" "$MYCURRDIR" &>/dev/null && return 0 || return 1; }
+  datecmd() { date +"${datetimeformat}${setvertype}"; }
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
   case $1 in
   -v | --version) __version ;;
   -h | --help) __help ;;
   esac
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
   if [ -d "$1" ]; then
     MYCURRDIR="$1"
     shift 1
@@ -54,34 +68,14 @@ main() {
   else
     MYCURRDIR="$PWD"
   fi
-  if [ "$MYCURRDIR" = "." ]; then MYCURRDIR="$(dirname "$PWD/." 2>/dev/null)"; fi
+  if [ "$MYCURRDIR" = "." ]; then MYCURRDIR="$(dirname ".")"; fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  if [ -d "$MYCURRDIR/.git" ]; then
-    printf_question "Are you sure as this WILL delete your local repo" [y/N]
-    read -r -n 1 -s clone && echo
-    if [[ $clone == "y" || $clone == "Y" ]]; then
-      printf_green "Cloning to $MYCURRDIR"
-      [ -d "$2" ] && rm_rf "$2"
-      if __git "$1"; then
-        printf_green "Cloning of $1 has succeeded"
-      else
-        printf_red "Cloning of $1 has failed"
-        exitCode=1
-      fi
-    else
-      printf_info "You have cancelled the current operation"
-      exitcode=1
-    fi
-  else
-    printf_green "Cloning to $MYCURRDIR"
-    if __git "$1"; then
-      printf_green "Cloning of $1 has succeeded"
-    else
-      printf_red "Cloning of $1 has failed"
-      exitCode=1
-    fi
-  fi
-  return ${exitCode:-$?}
+  case $1 in
+  *file) datecmd >"$MYCURRDIR/version.txt" ;;
+  *) datecmd ;;
+  esac
+
+  return "${exitCode:-0}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
